"use client";
import React, { useState } from "react";
import DropdownMenu from "./dropdownmenu";

interface TextInputProps {
  onInputChange: (newValue: string) => void;
}
export const TextInput: React.FC<TextInputProps> = ({ onInputChange }) => {
  const [inputValue, setInputValue] = useState("");

  const handleOptionSelect = (selectedOption: string) => {
    setInputValue(selectedOption);
  };

  const validWords = [
    "ABAZA G M",
    "ABBATE E C",
    "ABDOLEE R",
    "ABMAN Z",
    "ABNEY D P",
    "ABRA G J",
    "ABRAMS A S",
    "ABRAMSON T L",
    "ABU-OMAR M",
    "ABURQAYEQ G M",
    "ACEVEDO B P",
    "ACKERT E S",
    "ACKLEY C R",
    "ACOSTA-ALVEAR",
    "ADAMS A J",
    "ADAMS B",
    "ADAMS E E",
    "ADAMS J V",
    "ADLER-KASSNER",
    "ADORNETTO D",
    "AFARY J",
    "AFIFI T D",
    "AFIFI W A",
    "AGBOOLA A",
    "AGEY E R",
    "AGHAPOUR A A",
    "AGRAWAL D",
    "AGRAWAL S G",
    "AGUILAR M",
    "AHMAD A A",
    "AHMED J",
    "AHMED N S",
    "AHUJA A",
    "AIRAME S",
    "AKEMANN C A",
    "AKUDINOBI J",
    "AKULOV D A",
    "AL-BAHLOLY S",
    "ALAGONA P S",
    "ALANIZ D N",
    "ALAR D L",
    "ALBADA N A",
    "ALDANA G V",
    "ALESSIO P A",
    "ALHALABIEH D",
    "ALIZADEH M",
    "ALLEN M A",
    "ALMARAZ A",
    "ALMEROTH K C",
    "ALSALLOOM S",
    "ALSHAIF G A",
    "ALTHAUSER S B",
    "ALVES A R",
    "ALVES FERREIR",
    "ALVES J A",
    "ALZAGATITI J",
    "AMADO R",
    "AMAR P E",
    "AMARAL DE CAS",
    "AMAYA E C",
    "AMIHAY A",
    "AMIHAY O",
    "AMIN-HONG H",
    "ANANTH P V",
    "ANDERS A",
    "ANDERSON A K",
    "ANDERSON D D",
    "ANDERSON KE B",
    "ANDERSON O E",
    "ANDERSON R W",
    "ANDERSON S",
    "ANDERSSON E A",
    "ANDREA B D",
    "ANDUGAR SOUSA",
    "ANKRAH C N",
    "ANTONUCCI R R",
    "ANYIKA M",
    "APIGO A L",
    "APPEL I J",
    "APPINO-TABONE",
    "APPLEWHITE C",
    "ARAGON M J",
    "ARAI S",
    "ARAI W A",
    "ARALERE T S",
    "ARAUJO C M",
    "ARENAS VELAZQ",
    "ARGENT P",
    "ARGUERA S M",
    "ARIAS A A",
    "ARIAS GONZALE",
    "ARMBRUSTER R",
    "ARMISTEAD K J",
    "ARNOLD K A",
    "ARONOVA E A",
    "ARRINGTON E C",
    "ARVAS A",
    "ARVIZU RAMIRE",
    "ARYA D J",
    "ASCHE C B",
    "ASHBY F G",
    "ASI A",
    "ASWATHANARAYA",
    "ATHAYDE M A",
    "ATNIP L M",
    "ATWELL H R",
    "ATZBERGER P J",
    "AUE D H",
    "AUER M E",
    "AUNE A K",
    "AUNG T",
    "AVETISYAN Z",
    "AVILA A M",
    "AWADALLA C A",
    "AWRAMIK S M",
    "AYASSE A K",
    "AYUK-ETANG E",
    "AZARENKO O",
    "AZZAM T",
    "BABAKHANI A",
    "BACIU D C",
    "BADAMO H A",
    "BADLEY III D",
    "BAETGE N Q",
    "BAEZA CINCO M",
    "BAGHERI A R",
    "BAGWELL J N",
    "BAHAM M E",
    "BAIK J",
    "BAILEY C R",
    "BAILEY-STEINI",
    "BAILLARGEON K",
    "BAKER A D",
    "BAKER R R",
    "BAKI H A",
    "BAKO S C",
    "BALDWIN J D",
    "BALDWIN J I",
    "BALENTS L M",
    "BALKIND J M",
    "BALL R C",
    "BALLERINO J M",
    "BALLMES V J",
    "BAMBACH P A",
    "BAMIEH B A",
    "BANACH M",
    "BANERJEE K",
    "BANERJEE T",
    "BANG S",
    "BANKS I",
    "BANTA I C",
    "BAO H",
    "BAO K Q",
    "BAOAGUDAMU U",
    "BAPAT S R",
    "BARACALDO LAN",
    "BARANDIARAN J",
    "BARBIERI A J",
    "BAREI A",
    "BARLEY S R",
    "BARNES D B",
    "BARNETT M L",
    "BARNHART J",
    "BARNWELL B B",
    "BARRAGE L",
    "BARRAZA ALVAR",
    "BARRETT T W",
    "BARRY C M",
    "BARTER D E",
    "BARTOLINI A",
    "BARVOSA E",
    "BASHI TREITLE",
    "BATES C M",
    "BATHO D A",
    "BATISTE S L",
    "BATZ G",
    "BAUSCH T C",
    "BAX A C",
    "BAYLIS K R",
    "BAYRAKDARIAN",
    "BAZAN G C",
    "BAZERMAN C",
    "BEAMAN J M",
    "BEANE M I",
    "BECK L M",
    "BECKER M",
    "BECKMAN L B",
    "BEDARD K L",
    "BEDROV A",
    "BEGIN A L",
    "BEGLEY M R",
    "BELDING E M",
    "BELL V R",
    "BELLOMI J J",
    "BELMAR VIERNE",
    "BELTZ E A",
    "BELTZ G",
    "BEN YOUSSEF C",
    "BEN-YAACOV I",
    "BENELLI C A",
    "BENHAIM H S",
    "BENJAMIN R",
    "BENKLEY D A",
    "BENNAHUM D",
    "BENNETT M D",
    "BENNETT T D",
    "BENZARTI Y C",
    "BERENSTEIN D",
    "BERGSTROM R E",
    "BERGSTROM T C",
    "BERKOWITZ P M",
    "BERMUDEZ S",
    "BERNARD M A",
    "BERNSTEIN E K",
    "BERNSTEIN H J",
    "BERNSTEIN M M",
    "BERNT C M",
    "BEST B D",
    "BEYELER M",
    "BEYERLEIN I J",
    "BHAVNANI K",
    "BIANCHINI J A",
    "BIBILASHVILI",
    "BIELAK S",
    "BIELBY D D",
    "BIGELOW S J",
    "BILDSTEN L",
    "BIMBER B",
    "BIRCH A",
    "BIRCHENALL J",
    "BIRNIR B",
    "BLACKWELL K S",
    "BLAES O M",
    "BLAIN S M",
    "BLAKE F D",
    "BLANKHOLM J L",
    "BLAYLOCK R",
    "BLOOM P J",
    "BLUMENTHAL",
    "BLUMENTHAL D",
    "BLUMENTHAL S",
    "BLURTON H F",
    "BOBO J",
    "BOCCHINO A J",
    "BOCHEFF M M",
    "BODDY A M",
    "BOE B A",
    "BOGAN S N",
    "BOGAR L M",
    "BOGART K S",
    "BOGUNOVIC M C",
    "BOHN H",
    "BOLIVAR J",
    "BOONE R G",
    "BOOTH W C",
    "BORBA C R",
    "BORIS E C",
    "BOROWICZ L A",
    "BORROMEO C",
    "BORSA C",
    "BORUM A K",
    "BOSCAGLI M",
    "BOSWELL A M",
    "BOTHRA S",
    "BOULEY B A",
    "BOURNE J E",
    "BOUWMEESTER D",
    "BOWERS J E",
    "BOWERS M T",
    "BOWMAN I K",
    "BOYLAND P",
    "BRADLEY N D",
    "BRADY S R",
    "BRAININ R",
    "BRANDT G M",
    "BRANDT T D",
    "BRAUNSTEIN E",
    "BRECHER B H",
    "BREHM L E",
    "BREMSER C R",
    "BRENDEL C D",
    "BRENNER M E",
    "BREWER F",
    "BRICCETTI R E",
    "BRIDGES T S",
    "BRIGGS C J",
    "BRIGGS N A",
    "BRIGHT R",
    "BRIGHTBILL J",
    "BRITTON C J",
    "BROWN C E",
    "BROWN E",
    "BROWN F L",
    "BROWN J R",
    "BROWN K M",
    "BROWN KARA",
    "BROWN M",
    "BROWN M S",
    "BROWNE N C",
    "BROWNING R",
    "BRUHN K",
    "BRUICE A M",
    "BRUICE P Y",
    "BRUN J",
    "BRUSH A M",
    "BRUSUTTI A",
    "BRYSK A",
    "BRZEZINSKI M",
    "BUCHOLTZ M H",
    "BUCKWALTER J",
    "BUEHNER T D",
    "BUENDIA DE LL",
    "BUENO C",
    "BUENO CACHADI",
    "BUI A T",
    "BULLO F",
    "BULTAN T",
    "BUMBY A K",
    "BUMROONGCHART",
    "BUNTAINE M T",
    "BURATTO S K",
    "BURK K T",
    "BURKEPILE D E",
    "BURNES T R",
    "BURRIGHT G M",
    "BURSTON A S",
    "BURTNER S A",
    "BUSCHOR T L",
    "BUSTO R V",
    "BUTLER A",
    "BYL K A",
    "CABEZON J I",
    "CABIN Z A",
    "CABRANES-GRAN",
    "CABRERA PEREZ",
    "CAI Q",
    "CALDWELL S",
    "CALLAHAN R J",
    "CALLISTER J",
    "CAMPAGNARI C",
    "CAMPAS-RIGAU",
    "CAMPBELL E W",
    "CAMPO J E",
    "CAMPO M",
    "CAMSARI K Y",
    "CANET S H",
    "CANTRELL A M",
    "CAPETTINI E",
    "CAPLAN A N",
    "CARATELLI D",
    "CARLETON T A",
    "CARLINI A S",
    "CARLISLE E W",
    "CARLSON C A",
    "CARLSON J A",
    "CARLSON J M",
    "CARLSON T A",
    "CARLYLE A M",
    "CARMICHAEL J",
    "CARRETE A",
    "CARRILLO M J",
    "CARROLL T G",
    "CARTER A V",
    "CARTER D B",
    "CARTER M L",
    "CASE S H",
    "CASELLE J E",
    "CASILLAS D I",
    "CASSELS S L",
    "CASSIDY T C",
    "CAST A D",
    "CASTEELS K L",
    "CASTELLA-CABE",
    "CASTILLO J L",
    "CASTILLO-MUNO",
    "CASTLE R E",
    "CASTRIOTTA G",
    "CASTRO M M",
    "CATLETT D S",
    "CAVES E M",
    "CAYLOR K K",
    "CEDENO T H",
    "CENICEROS H",
    "CENICEROS R C",
    "CEREZO A",
    "CHABINYC M L",
    "CHADA J P",
    "CHADWICK O A",
    "CHAFFIN B M",
    "CHAGOLLA D",
    "CHAJDAS T W",
    "CHAMBERS R T",
    "CHAMORRO J D",
    "CHAN M",
    "CHAN N A",
    "CHANDRASEKARA",
    "CHANG A Y",
    "CHANG G",
    "CHANG SHIYU",
    "CHANG YU-CHI",
    "CHANTRE M A",
    "CHARITY-HUDLE",
    "CHARLES M",
    "CHARNESS G B",
    "CHARRY J D",
    "CHATTERJI A",
    "CHATTO U",
    "CHATTOPADHYAY",
    "CHAUHAN D",
    "CHAVEZ M V",
    "CHAVEZ W S",
    "CHAVEZ-GARCIA",
    "CHAVIRA A I",
    "CHEN C",
    "CHEN E",
    "CHEN H",
    "CHEN I",
    "CHEN J",
    "CHEN K Y",
    "CHEN MENG",
    "CHEN P",
    "CHEN S C",
    "CHEN T",
    "CHEN Y",
    "CHEN ZHITAO",
    "CHENEY C R",
    "CHENG Y",
    "CHENOWETH R C",
    "CHIKMAGALUR K",
    "CHIKOWERO M",
    "CHILDRESS J J",
    "CHILDRESS J N",
    "CHIN C A",
    "CHIN J",
    "CHIN M",
    "CHIRIKIAN O",
    "CHMELKA B F",
    "CHO A",
    "CHO G",
    "CHO J G",
    "CHOI E",
    "CHOW T Y",
    "CHRISTMAN D M",
    "CHRISTOFFERSE",
    "CHRISTOPHER P",
    "CHU S",
    "CHU V W",
    "CHUA C S",
    "CIFUENTES S R",
    "CISLO D J",
    "CLAIRMONT III",
    "CLARK J",
    "CLARK L N",
    "CLARKE K",
    "CLARKE M E",
    "CLAUSSEN N H",
    "CLAVERIA A J",
    "CLEGG D O",
    "CLEGG M B",
    "CLEMENCON R",
    "CLEMENT R J",
    "CLIFFORD A D",
    "CLITANDRE N T",
    "CLOOS C M",
    "COBB N A",
    "COBO BETANCOU",
    "COBRA LIMA L",
    "COBURN H P",
    "COBURN K M",
    "COFFEY EDISON",
    "COGGINS B L",
    "COHEN B J",
    "COHEN N A",
    "COKLIN L",
    "COLAHAN N",
    "COLBY J C",
    "COLES A P",
    "COLLINS N L",
    "COLLINS W J",
    "COMRIE B S",
    "COMSTOCK J A",
    "CONKLIN S L",
    "CONLEY S",
    "CONNER T M",
    "CONRAD N C",
    "CONRAD P T",
    "CONROY-BEAM D",
    "CONSOLI A J",
    "CONSTENLA TOR",
    "CONTE E A",
    "CONTRERAS E",
    "COOK E H",
    "COOK J N",
    "COOLEY T",
    "COOPER D",
    "CORONA K D",
    "CORREA DE SA",
    "CORTANA L",
    "CORTES P J",
    "CORTIJO A",
    "COSMIDES L",
    "COSTELLO C J",
    "COSTIGAN T J",
    "COTICH C",
    "COTTER E E",
    "COTTLE J",
    "COVO M",
    "COWANS N",
    "COWHIG F Y",
    "COX D D",
    "COX N M",
    "CRAIG K C",
    "CRAIG N J",
    "CRAVEIRO DE M",
    "CRAWSHAW A S",
    "CREMERS M H",
    "CRICKETTE M E",
    "CRISLER J F",
    "CROUCH C Q",
    "CROW E M",
    "CRUZ J D",
    "CSER A J",
    "CSIK S",
    "CULHANE K E",
    "CUMMINGS C R",
    "CURTIN M J",
    "CURTIN M L",
    "CURTY R G",
    "CYKMAN N N",
    "CZUCZOLA M",
    "D'ANCA C",
    "D'ANTONIO C M",
    "DAGLI N",
    "DAHL SARNELLI",
    "DAHLEN G A",
    "DAHLQUIST F W",
    "DAI X Z",
    "DALY S H",
    "DAMLUJI M N",
    "DANIEL R",
    "DANIELS E B",
    "DANNHAUSER M",
    "DASGUPTA D",
    "DAUM K L",
    "DAVID J S",
    "DAVIES M E",
    "DAVIS F W",
    "DAVIS N W",
    "DAVIS S L",
    "DAVISON R J",
    "DAY F J",
    "DE ALMEIDA A",
    "DE BRITO E SO",
    "DE CARVALHO L",
    "DE CHAISEMART",
    "DE FRUTOS GAR",
    "DE JONG M T",
    "DE LA PENA M",
    "DE SILVA N B",
    "DE SIMONE T",
    "DE TOMASO A W",
    "DEAN C W",
    "DEANGELO G M",
    "DEBRUHL B E",
    "DELCHEVA M P",
    "DELGADO HELLE",
    "DELOMBARD J M",
    "DENAUD E T",
    "DENBAARS S P",
    "DENG Z",
    "DERAKHSHANI D",
    "DERWIN S",
    "DESCHENES O",
    "DESGENS-MARTI",
    "DESHMUKH R A",
    "DESLIPPE P R",
    "DESPAIN C D",
    "DETERING N",
    "DEVOTO S A",
    "DEVOY M A",
    "DEVRIES M S",
    "DEVRIES T J",
    "DEWAR T J",
    "DEXTER TORTI",
    "DEY S S",
    "DIAZ-SANCHEZ",
    "DIB N",
    "DICKEY K M",
    "DICKSTEIN J H",
    "DIGESER E D",
    "DIGESER P",
    "DING Q",
    "DING YUFEI",
    "DIXON A L",
    "DIZEREGA L A",
    "DJOUINI I",
    "DO K N",
    "DODGE S",
    "DOGIC Z",
    "DOHERTY M F",
    "DOIRON F D",
    "DONELAN J H",
    "DONG X",
    "DONNELLY B",
    "DORNAN N N",
    "DOUGLAS P L",
    "DOUGLASS J H",
    "DOUGLASTAVANI",
    "DOWDY E T",
    "DOWDY K L",
    "DOWNING M E",
    "DOYLE A M",
    "DOYLE T",
    "DOZIER J C",
    "DRESSAIRE E M",
    "DRIAN J L",
    "DRISKEL D B",
    "DROGE A M",
    "DU BOIS J W",
    "DU Z",
    "DUAN J",
    "DUAN S",
    "DUCHESNE-PECK",
    "DUCK W",
    "DUCKLER H J",
    "DUDLEY T L",
    "DUDNEY J C",
    "DUFFY A E",
    "DUGAN J E",
    "DUNBAR N E",
    "DUNCAN I",
    "DUNCAN J E",
    "DUNN F M",
    "DUNNE S C",
    "DUOER D",
    "DUPLESSIS R J",
    "DUQUE J D",
    "DURAN R P",
    "DURKIN K",
    "DUTSCH D",
    "DYCK K V",
    "EARDLEY D M",
    "EBEN J P",
    "EBENSTEIN A O",
    "EBRAHIM E",
    "ECKSTEIN M P",
    "EDERER E B",
    "EDGAR A L",
    "EDWARDS A L",
    "EDWARDS J A",
    "EGECIOGLU O",
    "EIERS W J",
    "EILON Z C",
    "EK A A",
    "EKSTROM L",
    "EL ABBADI A",
    "EL OMARI R M",
    "EL-SOUSSI M H",
    "ELCHEIKHALI M",
    "ELDRIDGE R B",
    "ELIASON PARSO",
    "ELISON W N",
    "ELIZONDO E S",
    "ELLIOTT G",
    "ELLIS B D",
    "ELSAYED S H",
    "ELSHAFIY A",
    "ELTAWIL N A",
    "ELWELL K",
    "EMRE M",
    "ENDERS J",
    "ENGART H S",
    "ENGEL E A",
    "ENGLISH E D",
    "ENOCH M",
    "ENTESHARI F",
    "EPELBAUM D P",
    "ERDMAN C S",
    "ERICKSON B L",
    "ERICKSON E A",
    "ERNST B C",
    "ESCOLANO MARI",
    "ESLAMI RASEKH",
    "ESPONDA I",
    "ESTABROOK J A",
    "ETTENBERG A",
    "EVANS M M",
    "EVANS M U",
    "EVANSTEIN E K",
    "EVELYN C J",
    "EVEN T J",
    "EVERETT A",
    "EVERETT C J",
    "EXFORD J L",
    "EYELADE O D",
    "EYSTER E",
    "EZKERRA VEGAS",
    "FACCANI O",
    "FAELDONEA C F",
    "FAESSEL V A",
    "FAHLER M V",
    "FALASCA S",
    "FALLAS A",
    "FALVEY K T",
    "FANCHER P J",
    "FANG C",
    "FANTON M R",
    "FARRANT D N",
    "FARRELL R M",
    "FATHI S",
    "FAUST J M",
    "FAUST M R",
    "FAWCETT A Z",
    "FEASEL S H",
    "FEDDERS A",
    "FEINSTEIN S C",
    "FEIZMOHAMMADP",
    "FELANDO C L",
    "FELBER J",
    "FELDMAN D B",
    "FELDMAN J E",
    "FELDMAN R",
    "FELDMAN R H",
    "FELDWINN D L",
    "FELIX E D",
    "FENG J L",
    "FENG Y",
    "FENG YU",
    "FENRICH E B",
    "FERAUD M",
    "FERNANDEZ L",
    "FERNANDEZ M",
    "FERNANDEZ P A",
    "FESTA E",
    "FIDDLER M B",
    "FIELDS K",
    "FIELDS KEN",
    "FIELDS-MEYER",
    "FIGUEREDO O O",
    "FINE J C",
    "FINKELSTEIN R",
    "FINN E C",
    "FINNEY S",
    "FIORINA C P",
    "FISCHER J P",
    "FISHELL J K",
    "FISHER M A",
    "FISHER M P",
    "FISHER N",
    "FISHER R J",
    "FISHER S K",
    "FISHMAN A D",
    "FITCH R L",
    "FLANAGIN A J",
    "FLATLEY D J",
    "FLEMING W",
    "FLETCHER B J",
    "FLEURY I M",
    "FLORES I",
    "FLOWERS N Z",
    "FLUHMAN J S",
    "FOGU C",
    "FOLK-FARBER K",
    "FOLTZ K R",
    "FONTAINE D O",
    "FONTAINE S A",
    "FORAN J F",
    "FORBES E S",
    "FORD A",
    "FORD K C",
    "FORD P C",
    "FORE M R",
    "FORMAN J D",
    "FOUQUE J-P",
    "FOX E C",
    "FOX M S",
    "FRANITZA M C",
    "FRANK D M",
    "FRANKS A",
    "FRECH H E",
    "FREDRICKSON G",
    "FREE C",
    "FREEBURG S",
    "FREEBURG S A",
    "FREEDMAN R A",
    "FREEMAN L A",
    "FREUND E G",
    "FREW J E",
    "FRIDLUND A J",
    "FRIED B J",
    "FRIEDKIN N E",
    "FRIEDMAN U D",
    "FRODESEN J M",
    "FROEHLICH H E",
    "FROST G A",
    "FRUHSTUCK S",
    "FRYBERGER P D",
    "FRYER S",
    "FUENTES F X",
    "FUJINO D C",
    "FULBECK L K",
    "FULKERSON S D",
    "FULLAGER T K",
    "FUMERTON M P",
    "FYGENSON D K",
    "GABLE S",
    "GABRIEL V",
    "GABRIELE G F",
    "GABRIELSON C",
    "GAGNON E",
    "GAINER M J",
    "GAINES S",
    "GALAZ-GARCIA",
    "GALICIA M G",
    "GALISKY J A",
    "GALLUCCI R",
    "GAMARNIK D",
    "GAMBLE L H",
    "GAMELIN B L",
    "GANS P B",
    "GANTI N K",
    "GARBER A C",
    "GARBER N A",
    "GARCIA DAHAN",
    "GARCIA GONZAL",
    "GARCIA K",
    "GARCIA M",
    "GARCIA M T",
    "GARCIA S",
    "GARCIA-CERVER",
    "GARCIA-MARTIN",
    "GARDNER B M",
    "GARDNER C",
    "GARDNER H K",
    "GARFIELD P M",
    "GARFINKLE C G",
    "GARIBALDI H E",
    "GARR W R",
    "GARRATT R J",
    "GAULIN S J",
    "GAUTIER C H",
    "GAYEN M R",
    "GAZZANIGA M",
    "GEE Q P",
    "GELBART B J",
    "GELLER R M",
    "GENENS D W",
    "GENOVA G L",
    "GERMAN T C M",
    "GERSON S M",
    "GEYER R",
    "GHOSAL A",
    "GHOSH B",
    "GIAMBONI G",
    "GIANOLA D S",
    "GIBBS J L",
    "GIBBS W C",
    "GIBOU F G",
    "GIBSON J D",
    "GIBSON S E",
    "GIDDING A D",
    "GIDDINGS S B",
    "GIESBRECHT B",
    "GIESSINGER E",
    "GILBERT J R",
    "GILES H",
    "GILES M N",
    "GILLILAND K L",
    "GILMORE T B",
    "GLASSOW M A",
    "GLOVER Y H",
    "GOARD M",
    "GODDARD E L",
    "GODDARD T U",
    "GOFFARD P M",
    "GOLDSTEIN S H",
    "GOLUBOVIC N",
    "GOMEZ D M",
    "GOMEZ J P",
    "GOMEZ Y",
    "GONZALES A L",
    "GONZALES G G",
    "GONZALES-SMIT",
    "GONZALEZ I N",
    "GONZALEZ J C",
    "GONZALEZ J H",
    "GONZALEZ NINO",
    "GONZALEZ T A",
    "GOOD F E",
    "GOODEARL K",
    "GOODWIN J W",
    "GOPALAN G",
    "GORDON A F",
    "GORDON M J",
    "GORDON M K",
    "GORDON R W",
    "GOTO E A",
    "GOTTFRIED M A",
    "GOUGH J D",
    "GOULIAS K",
    "GRABOVSKY D J",
    "GRAFTON S T",
    "GRASSET MOREL",
    "GRAVES G R",
    "GRAY J L",
    "GRAY S M",
    "GREATHOUSE J",
    "GRECO A L",
    "GREENE A R",
    "GREENE B L",
    "GREGO MARCH C",
    "GRIBBLE J W",
    "GRIES S T",
    "GRIESSBAUM N",
    "GRIFFIN A R",
    "GRIFFITH B J",
    "GRIFFITH D K",
    "GRIMES N G",
    "GRIPPO J R",
    "GROSS M E",
    "GROSS S L",
    "GROVER S R",
    "GRUE M N",
    "GU M",
    "GUAN D",
    "GUAN M",
    "GUHA P",
    "GUILLIAMS C M",
    "GUIRGUIS C M",
    "GUO QIHENG",
    "GUPTA A",
    "GUPTA T",
    "GURUSWAMY S",
    "GURVEN M D",
    "GUTIERREZ-MAG",
    "GUTMAN K L",
    "GUYTON ACOSTA",
    "HABER B W",
    "HACKER B R",
    "HAI J",
    "HAI Y",
    "HAIDER J E",
    "HAJDA J M",
    "HAJJAR L",
    "HAJOUJI N",
    "HALL A J",
    "HALL M M",
    "HALMRAST D M",
    "HALPERN B S",
    "HAMAD S",
    "HAMBLETON E J",
    "HAMED-TROYANS",
    "HAMILTON K A",
    "HAMILTON N C",
    "HAMMER L M",
    "HAN SONGI",
    "HANCOCK M E",
    "HANEIN D",
    "HANNAH L J",
    "HANSCHMANN J",
    "HANSEN G S",
    "HANSEN K D",
    "HANSER M F",
    "HANSIA A D",
    "HANSIA M S",
    "HANSMA P K",
    "HANSON J L",
    "HARBER J J",
    "HARDEKOPF B C",
    "HARDESTY MOOR",
    "HARLOW D B",
    "HARMON C J",
    "HARRICHHAUSEN",
    "HARRIS D R",
    "HARRIS O",
    "HARRIS S Y",
    "HARRIS-GAVIN",
    "HARRIS-MOORE",
    "HARRISON L S",
    "HARTER J W",
    "HARTHORN B H",
    "HARTMAN J L",
    "HARUTYUNYAN D",
    "HARVEY V A",
    "HASHIMOTO K",
    "HASTINGS S P",
    "HATCHER K L",
    "HAUGHIN C A",
    "HAUGHTON C N",
    "HAWKER C J",
    "HAWKES E W",
    "HAYDEN N",
    "HAYES C S",
    "HAYNE R M",
    "HAYNES R M",
    "HAYTON T W",
    "HE C",
    "HE J",
    "HEBDIGE R W",
    "HECHT R",
    "HEGARTY M",
    "HEILBRON A P",
    "HEILMAYR R F",
    "HEINRICH S E",
    "HEINTZ M A",
    "HELGESON M E",
    "HELLIER-TINOC",
    "HENDERSON A M",
    "HENDERSON G L",
    "HENDERSON J G",
    "HENDERSON O G",
    "HENNAWI J F",
    "HERNANDEZ E D",
    "HERRERA D J",
    "HERTLER P R",
    "HESPANHA J P",
    "HEY M V",
    "HIEBERT L S",
    "HIGGINS V B",
    "HILLEN P K",
    "HILLIS G A",
    "HILTNER K C",
    "HIRSCH M",
    "HIRSCH S A",
    "HIXSON M L",
    "HOBBS-MORGAN",
    "HOCK M A",
    "HODGES H E",
    "HODGES S A",
    "HOELLE J A",
    "HOERBERG D L",
    "HOFMANN G E",
    "HOFMANN M J",
    "HOGENSON L A",
    "HOLBROOK S J",
    "HOLCOMB S J",
    "HOLDEN P A",
    "HOLDEN T",
    "HOLDEN T A",
    "HOLDREGE B A",
    "HOLDREN N R",
    "HOLGUIN A",
    "HOLLERER T",
    "HOLMAN A C",
    "HOLMES D E",
    "HOLMES T J",
    "HOLT J",
    "HOLTON J D",
    "HOM S M",
    "HONG C",
    "HOPKINS A C",
    "HOPP F R",
    "HOPPER J T",
    "HOROWITZ E J",
    "HOROWITZ G",
    "HORST A M",
    "HOU L Y",
    "HOUGH K C",
    "HOWELL D A",
    "HSU C-C",
    "HSU S J",
    "HU M",
    "HU R",
    "HU S B",
    "HU T",
    "HUANG JINXI",
    "HUANG YU",
    "HUBER C F",
    "HUGHES D L",
    "HUISGEN-ZIMME",
    "HUK P M",
    "HULME J L",
    "HUMPHREY S F",
    "HUNNICUTT P L",
    "HURTADO A",
    "HUSTON V G",
    "HUYNH-TRAN K",
    "HWANG S",
    "ICHIBA T",
    "IGLESIAS-RODR",
    "IGNON M E",
    "IHLENDORF BUR",
    "IHM E D",
    "IKEUCHI S",
    "IMMEL B A",
    "INGHAM R J",
    "INNES-GOLD S",
    "IOANNIDES M J",
    "ISRAEL T",
    "ISUKAPALLI Y",
    "ITO R A",
    "IUM M H",
    "JACK B K",
    "JACK M Z",
    "JACKS W A",
    "JACKSON M G",
    "JACKSON W E",
    "JACOB W B",
    "JACOBS E",
    "JACOBS J M",
    "JACOBS J P",
    "JACOBS R E",
    "JACOBSON L",
    "JACQUES G F",
    "JAEGER L A",
    "JAHNKE A",
    "JAMES A K",
    "JAMES A M",
    "JAMESON-ELLSM",
    "JAMIESON A E",
    "JAMMALAMADAKA",
    "JAN K L",
    "JANEE G A",
    "JANES L",
    "JANG J",
    "JANOWICZ K W",
    "JANSON M A",
    "JANUSONIS S",
    "JAQUA K M",
    "JARAMILLO N",
    "JARRETT G C",
    "JASECHKO S A",
    "JASKIEWICZ A",
    "JAYICH A M",
    "JAYICH ANIA",
    "JENKINS C L",
    "JENSEN A K",
    "JENSEN A M",
    "JENSEN S J",
    "JEONG H",
    "JERDE C L",
    "JEVBRATT L V",
    "JI C",
    "JI X",
    "JIANG L",
    "JIANG X",
    "JIMENEZ CHAVE",
    "JIMERSON S R",
    "JIN C",
    "JIN Y",
    "JIN Z",
    "JIVRAJANI A",
    "JOB M",
    "JOHNS J W",
    "JOHNSON A Y",
    "JOHNSON AMRAH",
    "JOHNSON G B",
    "JOHNSON J A",
    "JOHNSON J K",
    "JOHNSON J M",
    "JOHNSON J R",
    "JOHNSON JULIE",
    "JOHNSON M J",
    "JOHNSON N",
    "JOHNSON N R",
    "JONES B",
    "JONES C",
    "JONES C E",
    "JOSEPH C A",
    "JOSEPH N",
    "JOSHI P M",
    "JOSTES J C",
    "JOURNEY A N",
    "JUE M C",
    "JUERGENSMEYER",
    "JULLIEN D M",
    "JURKOWSKI N W",
    "KACZMAREK A R",
    "KAGAN-MOORE H",
    "KAHN K",
    "KALE S K",
    "KALMAN L",
    "KAM J A",
    "KAMAL-HEIKMAN",
    "KAMANDY M",
    "KAMMEYER C L",
    "KAO Y",
    "KAPLAN A K",
    "KAPLAN C S",
    "KAPLAN R E",
    "KAPLAN S C",
    "KARVELAS B A",
    "KASOWSKI J M",
    "KASSNER N M",
    "KATSIKA A",
    "KATZ B N",
    "KATZ D H",
    "KATZ I T",
    "KATZ T S",
    "KAUFFMAN M E",
    "KAVON C D",
    "KAWAI A",
    "KAYAL S",
    "KAYLOR S M",
    "KAYSEN B J",
    "KEARNEY J J",
    "KEIFLIN R P",
    "KELEHER A",
    "KELLER A A",
    "KELLER E A",
    "KELLETT I A",
    "KENDALL B E",
    "KENNEDY R A",
    "KENNETT D J",
    "KENNON A M",
    "KESSLER K E",
    "KEUM T",
    "KEYNEJAD N",
    "KEYNEJAD N P",
    "KEZHAYA A M",
    "KHAIRALLAH S",
    "KHARITONOVA Y",
    "KHOSHBIN M",
    "KHOURY N N",
    "KHUC T T",
    "KIA-KEATING M",
    "KIBLER C L",
    "KILEY J T",
    "KILLEEN S M",
    "KIM B",
    "KIM H S",
    "KIM HAEWON",
    "KIM HYUN-JUNG",
    "KIM K",
    "KIM L",
    "KIM S",
    "KIM Y",
    "KIM YEWEON",
    "KIM YOUNG JI",
    "KIMBALL G R",
    "KIME S L",
    "KING  J L K",
    "KING B K",
    "KING D A",
    "KING J L",
    "KING J Y",
    "KING R S",
    "KING S L",
    "KING W D",
    "KING Z T",
    "KIPPIN T E",
    "KIRKBY J M",
    "KIRKWOOD G L",
    "KIRTMAN B",
    "KISLENKO N",
    "KITTLER W D",
    "KLAMKIN J",
    "KLAR T S",
    "KLEIN D S",
    "KLEIN S B",
    "KLEMANN D T",
    "KLING T P",
    "KLOETZEL J M",
    "KLOKE J",
    "KLOPE M M",
    "KNIGHT K T",
    "KOC C K",
    "KOENIG R J",
    "KOHLER K M",
    "KOKINIS T A",
    "KOLSTAD C D",
    "KOMMERELL G",
    "KONTTINEN O R",
    "KOPECKY K L",
    "KORATTI CHENG",
    "KORMAN D Z",
    "KORNBERG D N",
    "KOSIK K S",
    "KOSZEGI G K",
    "KOTH M K",
    "KOUTROULAKIS",
    "KOVACS P H",
    "KOZAL L C",
    "KOZERAWSKI J",
    "KRAMER S A",
    "KRASKURA K",
    "KRAUSE P A",
    "KRETZ D",
    "KRINTZ C",
    "KRISHNAMOORTH",
    "KRISTIANSEN K",
    "KROP L J",
    "KRUEGEL C I",
    "KRUKOWSKI J P",
    "KRUT R M",
    "KRUVAND M",
    "KRYDER E A",
    "KUCHERA-MORIN",
    "KUHN P J",
    "KUHN W",
    "KULKARNI S S",
    "KULPER D E",
    "KUMAR A U",
    "KUMAR S L",
    "KUNAK E",
    "KUNDU M",
    "KUNKEL B M",
    "KURGAN S",
    "KURIN D S",
    "KURIS A M",
    "KUZIN M",
    "KYLER B E",
    "KYRATZIS A",
    "LABARRE J",
    "LABATUT M A",
    "LABUTIN D A",
    "LAGUETTE S W",
    "LAHIRI S",
    "LAI K",
    "LAMARTINE N C",
    "LAMB R C",
    "LAMBERT A M",
    "LAMBERT R",
    "LAMBERT S K",
    "LAMON S E",
    "LANAHAN-KALIS",
    "LANDE E S",
    "LANDFIELD K M",
    "LANDRY T B",
    "LANDSTROM E B",
    "LANE D S",
    "LANE K V",
    "LANE S S",
    "LANSING C L",
    "LANUZA Y R",
    "LAPATE R C",
    "LAREZ N A",
    "LARIMIAN S",
    "LARIOS CARDEN",
    "LARRA?AGA K D",
    "LARRAAGA K D",
    "LARRANAGA K D",
    "LARSEN A E",
    "LARUE R J",
    "LASHMET A J",
    "LASSWELL S E",
    "LATTO J G",
    "LAU Q",
    "LAURENT-PERRA",
    "LAVERMAN L E",
    "LAWRENCE E J",
    "LAWRIE S I",
    "LAWSON A P",
    "LAWSON D W",
    "LEA D W",
    "LEACH R K",
    "LEACH T S",
    "LEANO J E",
    "LEAPER L",
    "LEARMAN R R",
    "LEBRUN A S",
    "LEE H",
    "LEE HYEONGSEO",
    "LEE J S",
    "LEE J W",
    "LEE M",
    "LEE M H",
    "LEE M J",
    "LEE S",
    "LEE W A",
    "LEE Y",
    "LEE YU-HSUAN",
    "LEGRADY G T",
    "LEHMAN K E",
    "LEN S M",
    "LENIHAN H S",
    "LEOMBRUNI L V",
    "LEONARDI P M",
    "LEPISSIER A M",
    "LEQUESNE T F",
    "LERNER M K",
    "LESLIE S M",
    "LEVENTI M",
    "LEVI C G",
    "LEVINE S",
    "LEVY B R",
    "LEW G J",
    "LEW Z J",
    "LEWALLEN A",
    "LEWIN B A",
    "LEWIN R J",
    "LEWIS J D",
    "LEWIS K",
    "LEWIS R B",
    "LEZRA E M",
    "LI B",
    "LI C Y",
    "LI G",
    "LI LEI",
    "LI P",
    "LI T",
    "LI X",
    "LI XIANG",
    "LI ZHIJIAN",
    "LIAO B",
    "LIBERMAN Z E",
    "LICHTENSTEI N",
    "LIEN P",
    "LIM G",
    "LIM S",
    "LIN HUIJIA",
    "LIN Q",
    "LIN SHIXING",
    "LINDHEIM S H",
    "LINDSAY R B",
    "LINK R A",
    "LINLEY S C",
    "LINZ D G",
    "LIPMAN E A",
    "LIPPINCOTT W",
    "LIPSHUTZ B H",
    "LIPSITZ G R",
    "LISIECKI L E",
    "LITTLE R D",
    "LIU A Y",
    "LIU D",
    "LIU M",
    "LIU N",
    "LIU ROBIN",
    "LIU W",
    "LIU Z",
    "LMAIFI M",
    "LOAICIGA H",
    "LOE-STERPHONE",
    "LOHWASSER K",
    "LOKE S",
    "LOKSHTANOV D",
    "LOMAX D",
    "LOMBARDINO M",
    "LOMELI F A",
    "LONERGAN C A",
    "LONG D D",
    "LONG R W",
    "LOPATKO E",
    "LOPEZ A",
    "LOPEZ A N",
    "LOPEZ C",
    "LOPEZ VERA A",
    "LOPEZ-ALVES F",
    "LOPEZ-CARR D",
    "LORIN DE LA G",
    "LOSTER D R",
    "LOUIS M R",
    "LOVE N L",
    "LOVE-ANDEREGG",
    "LOVELL J M",
    "LOVELY K R",
    "LOVERING J",
    "LOVETT D W",
    "LOVETT L",
    "LOVING LICHTE",
    "LOW D A",
    "LOW S H",
    "LOWAN-TRUDEAU",
    "LOWELL J F",
    "LU D",
    "LU Y",
    "LUBIN P",
    "LUDKOVSKI M",
    "LUDWIG A W",
    "LUKAS A V",
    "LUMBRERAS M",
    "LUNA J M",
    "LUNA Z T",
    "LUNDBERG S J",
    "LUNSFORD K J",
    "LUO X",
    "LUPI J P",
    "LUZZATTO-FEGI",
    "LYONS C D",
    "LYONS M M",
    "LYTLE T J",
    "MA D",
    "MA Y",
    "MA YUEYUAN",
    "MAAR H R",
    "MACARIO H",
    "MACDONALD A J",
    "MACDONALD F A",
    "MACGILLIVRAY",
    "MACHARIA C W",
    "MACIAS R",
    "MACINTYRE S",
    "MACKIE D M",
    "MACLEAN R B",
    "MACMAHON C M",
    "MADHOW U",
    "MAHAN M J",
    "MAHDAVI P",
    "MAHERAS A L",
    "MAHOWALD K A",
    "MAIER D J",
    "MAIER J A",
    "MAITY S",
    "MAJEWSKI J D",
    "MAJOR B N",
    "MALDONADO FAB",
    "MALDONADO J K",
    "MALEUVRE D",
    "MALHOTRA A",
    "MALLOY C J",
    "MALONE H S",
    "MALVINNI D",
    "MANCA G",
    "MANCINI D G",
    "MANIN F",
    "MANISCALCO M",
    "MANJUNATH B S",
    "MANOUDAKI N",
    "MANSKI B R",
    "MANSOUR O",
    "MARCHANT E A",
    "MARCHETTI M",
    "MARCOULIDES G",
    "MARCUS S L",
    "MARCUSE H",
    "MARDEN J R",
    "MARINA M M",
    "MARINO W F",
    "MARKS T G",
    "MAROLF D M",
    "MARQUES GARCI",
    "MARQUES-PASCU",
    "MARQUIS S M",
    "MARSANO V L",
    "MARSHALL K",
    "MARTELLA A M",
    "MARTIN C L",
    "MARTIN D",
    "MARTIN J A",
    "MARTIN MINANA",
    "MARTINEZ A A",
    "MARTINS N C",
    "MARTINS RODRI",
    "MARTINS SILVA",
    "MARZBAN E P",
    "MASANET E R",
    "MASLAN M J",
    "MASON E J",
    "MASSIE E K",
    "MASSIE J L",
    "MASTERSON D T",
    "MASTRO D E",
    "MATNI Z A",
    "MATOZA R S",
    "MATTHYS E F",
    "MAUL A E",
    "MAVRAKIS L J",
    "MAYER C",
    "MAYER R E",
    "MAYES B J",
    "MAYS K C",
    "MAZANEC T J",
    "MAZAROLI D N",
    "MAZER S J",
    "MAZIN B A",
    "MAZUR A P",
    "MAZZA R",
    "MCALLISTER L",
    "MCALPIN-LEVIT",
    "MCAULEY C",
    "MCBRIEN K M",
    "MCCAMMOND J P",
    "MCCANTS K A",
    "MCCARTHY C R",
    "MCCAULEY D J",
    "MCCLAIN K L",
    "MCCLELLAND-CO",
    "MCCLURE S B",
    "MCCRACKEN E",
    "MCCRACKEN L M",
    "MCCRAY W P",
    "MCDONALD K L",
    "MCFADDEN J P",
    "MCFARLAND E W",
    "MCGRATH A J",
    "MCGRATH G P",
    "MCHUGH P",
    "MCINTOSH D G",
    "MCKEE K D",
    "MCKENZIE N",
    "MCKINNEY D R",
    "MCKIRAHAN R D",
    "MCLAUGHLIN J",
    "MCLELLAN L",
    "MCLEMORE E L",
    "MCLEOD C N",
    "MCMAHON C A",
    "MCMAHON C S",
    "MCMEEKING R M",
    "MCMURTREY M J",
    "MCNAMARA J P",
    "MCNIFF A C",
    "MCQUILKIN C R",
    "MEADOW M A",
    "MEDINA A",
    "MEDINA R W",
    "MEDRI E E",
    "MEHRZADFAR H",
    "MEHTA A S",
    "MEHTA D M",
    "MEIBURG E H",
    "MEIER V C",
    "MEINHART C",
    "MEIRING W",
    "MEJIA BECERRA",
    "MELACK J M",
    "MELNICK R D",
    "MELTON M A",
    "MENA H P",
    "MENARD G",
    "MENDES BRAGA",
    "MENDEZ MURILL",
    "MENDEZ S C",
    "MENDOZA D",
    "MENDOZA M D",
    "MENG K C",
    "MERK M W",
    "MERKL K E",
    "MERMELSTEIN S",
    "MEROLLA A J",
    "MESROP L Y",
    "MESSNER M S",
    "METIU H I",
    "METZGER M J",
    "MEUNIER M M",
    "MEYER M N",
    "MEYER-GUTBROD",
    "MEYR J E",
    "MEZIC I",
    "MIELE I",
    "MIESCHER S F",
    "MIGLIO V G",
    "MIKAYELYAN H",
    "MILDENBERGER",
    "MILEM J F",
    "MILES-HERCULE",
    "MILJANICH C P",
    "MILLAR-BLANCH",
    "MILLER J B",
    "MILLER J E",
    "MILLER K M",
    "MILLER M B",
    "MILLER M J",
    "MILLER R J",
    "MILLER-LIKHET",
    "MILLER-YOUNG",
    "MILLETT K C",
    "MILLNER A M",
    "MINER M A",
    "MINOR R H",
    "MIOLANE N",
    "MIRACLE J W",
    "MIRELES M A",
    "MIRZA D",
    "MIRZAEI M",
    "MISHRA U",
    "MISRA N",
    "MITCHELL G M",
    "MITCHELL S T",
    "MITHUN M",
    "MITTELSTET A",
    "MIZRAHI J L",
    "MOAK D",
    "MOCK M U",
    "MOEHLIS J M",
    "MOELLER H V",
    "MOERSCHEL J A",
    "MOHAN A",
    "MOKRISKI D A",
    "MOLANDER M A",
    "MOLINA-ROGERS",
    "MONAHAN L",
    "MONDRAGON D M",
    "MONROE S L",
    "MONTAGUE D K",
    "MONTELL C",
    "MONTELL D J",
    "MONTELLO D R",
    "MONTINI T L",
    "MOODY G A",
    "MOORE J",
    "MOORE J S",
    "MOORE K",
    "MOORE K A",
    "MOORE K C",
    "MOORE K E",
    "MOORE K M",
    "MOOSBRUGGER L",
    "MORA E G",
    "MORAGA C L",
    "MORALES C T",
    "MORALES H L",
    "MORALES N",
    "MORAN A S",
    "MOREIRA V S",
    "MOREJON C",
    "MORELL K D",
    "MORELL SALCED",
    "MORENO CAMPOS",
    "MORENO PLASCE",
    "MORET S L",
    "MORGAN M",
    "MORGAN M L",
    "MORGENSTERN T",
    "MORLAND P",
    "MORRIS N S",
    "MORRIS S C",
    "MORRISON D R",
    "MORRISSEY M A",
    "MORSE D E",
    "MORSE J C",
    "MORSTEIN-MARX",
    "MORTON C",
    "MORTON D N",
    "MOSELEY D",
    "MOSER A C",
    "MOSER C H",
    "MOSKOVITS M",
    "MOSKOWITZ R A",
    "MOSTOFI Y C",
    "MOULTON S M",
    "MOUMINOUX C",
    "MOUTI S",
    "MOVSESIAN H",
    "MOXLEY C M",
    "MRAZEK A J",
    "MRAZEK M D",
    "MUIR C F",
    "MUKHERJEE ARN",
    "MUKHERJEE K",
    "MUKHERJEE S",
    "MULFINGER J",
    "MULLATH MOHAM",
    "MULLEN J O",
    "MULLER E B",
    "MULLIN C D",
    "MULLIN C R",
    "MULLIN D I",
    "MUNASINGHE A",
    "MUNK E N",
    "MURGIDA L J",
    "MURNANE E H",
    "MURRAY A",
    "MURRAY D A",
    "MURTI-HALI D",
    "MURUAMENDIARA",
    "MUZAMMAL M",
    "MYERS J",
    "MYERS K K",
    "MYERS P M",
    "MYUNG JIYOUN",
    "NABI R L",
    "NADLER R",
    "NAGY A",
    "NAKAMURA J C",
    "NALL C M",
    "NARANG N",
    "NASH D",
    "NATHAN J S",
    "NAUGHTON S J",
    "NAVICK N",
    "NAYAK C V",
    "NEDERVEEN PIE",
    "NEDJAT-HAIEM",
    "NEIDLINGER J",
    "NELSON H",
    "NELSON T A",
    "NERELLA T",
    "NERSTAD E L",
    "NESBIT D M",
    "NESCI C",
    "NEWBERRY K S",
    "NEWFIELD C J",
    "NGO H N",
    "NGUYEN A T",
    "NGUYEN D",
    "NGUYEN H-A T",
    "NGUYEN T T",
    "NHAN D Q",
    "NI Y",
    "NICHOLS A M",
    "NICHOLS J N",
    "NICHOLS L H",
    "NICOLAESCU A",
    "NIDZIEKO N J",
    "NIEHUSEN K P",
    "NIELSEN E S",
    "NINH E K",
    "NOE S J",
    "NOGUERA J M",
    "NOI A",
    "NOI E",
    "NORRIS A",
    "NORRIS L F",
    "NORTH M F",
    "NORTH R H",
    "NORTON P R",
    "NOURIZADEH S",
    "NOVAK D E",
    "NOVAK M J",
    "NOWAK J J",
    "NOWICKI S",
    "NYLUND K L",
    "O'CONNOR A M",
    "O'HARA C C",
    "O'HARA J D",
    "O'MALLEY M A",
    "OAKLEY T H",
    "OAKS L M",
    "OCAMPO C",
    "OCHOA F J",
    "OFFERT F",
    "OGBECHIE S O",
    "OGRAIN C M",
    "OH S P",
    "OH SANG-YUN",
    "OKAMOTO Y",
    "OLARTE T M",
    "OLGUIN B V",
    "OLGUIN MARTIN",
    "OLIVEIRA J P",
    "OLIVER E V",
    "OLIVER R Y",
    "ONAKADO M",
    "OONO R",
    "OPREA R D",
    "ORDONEZ O",
    "ORLANDO M D",
    "ORME-STONE C",
    "ORNELAS A",
    "ORR D A",
    "ORTIZ A",
    "ORTOSKY L E",
    "ORZEL C H",
    "OSBORNE G",
    "OSQUEEZADEH B",
    "OSUNA A R",
    "OTA K H",
    "OTMAR C D",
    "OVERTON K K",
    "OXELSON E M",
    "OZUNA C S",
    "PABLO S R",
    "PACHECO R",
    "PADILLA D Y",
    "PADILLA GONZA",
    "PADILLA M",
    "PADILLA-GARCI",
    "PADULA V",
    "PAGE H M",
    "PAJAK A K",
    "PAKRAVAN S",
    "PALLADINO J N",
    "PALLAPROLU A",
    "PALMSTROM C J",
    "PAN J",
    "PANDYA S P",
    "PAPADAKIS V",
    "PAPOLIYAZDI A",
    "PARDO GAVIRIA",
    "PAREDES-RIVER",
    "PARHAMI B",
    "PARIKH S",
    "PARISON A L",
    "PARK I W",
    "PARK J",
    "PARK J S W",
    "PARK L S",
    "PARK M",
    "PARK S",
    "PARK SIHWA",
    "PARKER C S",
    "PARKER E T",
    "PARKER M",
    "PARKER N A",
    "PARKS L A",
    "PARKS M M",
    "PARRA M A",
    "PARRISH C R",
    "PARTHASARATHY",
    "PARTOANDAZAN",
    "PATEL P P",
    "PATTERSON D S",
    "PATTERSON K A",
    "PATTERSON K V",
    "PATTONE C F",
    "PAUL C",
    "PAUL D C",
    "PAYNE T A",
    "PEACH K",
    "PEDARSANI R",
    "PEDERSEN H W",
    "PELJHAN M",
    "PELLOW D N",
    "PENABELLA M A",
    "PENLEY C",
    "PENNATHUR S",
    "PENNER K M",
    "PENNEY D J",
    "PENNINGTON H",
    "PENSERINI B D",
    "PEREZ E",
    "PEREZ TORRES",
    "PERKINS C",
    "PERRONE D",
    "PERRONE G",
    "PETERS G W",
    "PETERS J R",
    "PETERS S L",
    "PETERSEN A M",
    "PETERSON C L",
    "PETERSON S",
    "PETRO G",
    "PETRO G Z",
    "PETRO P S",
    "PETTERSSON PE",
    "PETTUS T R",
    "PETZOLD L",
    "PHILLIPS A A",
    "PHILLIPS D W",
    "PHILLIPS M E",
    "PHILLIPS N W",
    "PIERCE A M",
    "PIERCE K T",
    "PIERCE S G",
    "PILAFIAN C",
    "PINCUS P A",
    "PINHEIRO DE O",
    "PITENIS A A",
    "PIZANO N K",
    "PLANE A M",
    "PLANTINGA A",
    "PLASENCIA M",
    "PLAXCO K W",
    "PLUDOW B A",
    "POLATIS K N",
    "POLLOCK T M",
    "PONCE G",
    "POOLE S J",
    "POOT-HERRERA",
    "POPESCU P F",
    "PORTER M J",
    "PORTER S M",
    "POTOSKI M",
    "POTTER W J",
    "POWERS R T",
    "PRENTICE WALZ",
    "PRESS C M",
    "PRICE S P",
    "PRIETO E",
    "PRIVITERA-JOH",
    "PROPEN A D",
    "PROULX S R",
    "PRUITT B",
    "PRUITT J N",
    "PU J P",
    "PUENTE M",
    "PUGMIRE J E",
    "PULVER S",
    "PUTINAR M",
    "PYE L",
    "QI L",
    "QIN C Z",
    "QIN YAO",
    "QUEVEDO A M",
    "QUICK J D",
    "QUILLIEN T E",
    "QUINTANA A C",
    "QUIRK M P",
    "QUIROS W",
    "RACINE P E",
    "RADDE H D",
    "RADEMACHER S",
    "RADFORD A",
    "RADNA R",
    "RAGHU P",
    "RALEY R M",
    "RAMBELLI F",
    "RAMIEREZ J F",
    "RAMIREZ AMARA",
    "RAMIREZ B E",
    "RAMIREZ E M",
    "RAMIREZ MENDE",
    "RAMIREZ N M",
    "RAMIREZ RESTR",
    "RAMIREZ Y",
    "RAMOS M",
    "RANA S",
    "RAPOSO E",
    "RAPPAPORT E D",
    "RARESHIDE E",
    "RATNER K G",
    "RAVAT U V",
    "RAVEN M R",
    "RAWLINGS J B",
    "RAYCHAWDHURI",
    "RAYMOND E",
    "RAYMOND G",
    "RAZEK R D",
    "RAZIZADEH N",
    "RAZOR S",
    "READ DE ALANI",
    "REBICH S R",
    "REDDICK B",
    "REDER E R",
    "REESE B E",
    "REEVE D J",
    "REHNBERG N M",
    "REICH N O",
    "REID B T",
    "REID S A",
    "REID S C",
    "REIMER N",
    "REITZ Z L",
    "RENUKA BALAKR",
    "RESNICK E F",
    "RESTREPO I C",
    "REYES E R",
    "REYES M A",
    "REYNOLDS D F",
    "RIAZI T",
    "RICCI F",
    "RICE A M",
    "RICE R E",
    "RICHARDSON C",
    "RICHARDSON M",
    "RICHMAN J D",
    "RIEDMAN L A",
    "RIGHTMIRE S R",
    "RINN D W",
    "RIOS R M",
    "RIOS V M",
    "RIOUX M E",
    "RITTER G",
    "RIVAS J M",
    "ROA D E",
    "ROADS C",
    "ROBBINS M J",
    "ROBERTS C K",
    "ROBERTS D A",
    "ROBERTS L S",
    "ROBERTS S A",
    "ROBERTS S C",
    "ROBERTSON J L",
    "ROBERTSON T",
    "ROBINSON M A",
    "ROBINSON S L",
    "ROBINSON W I",
    "ROCHAT M J",
    "RODRIGUEZ C H",
    "RODRIGUEZ E J",
    "RODRIGUEZ VEG",
    "RODRIGUEZ-VIL",
    "RODWELL M J",
    "ROEHRICH B W",
    "ROEPE M W",
    "ROGERS P G",
    "ROGERS P M",
    "ROHRER K A",
    "ROMINE J T",
    "ROMO L F",
    "RONEY J R",
    "ROOSE H M",
    "ROSE K",
    "ROSE M A",
    "ROSEDAHL L A",
    "ROSES LABRADA",
    "ROSS ALTARAC",
    "ROSS E G",
    "ROTHFARB L A",
    "ROTHMAN J H",
    "ROTTNER R M",
    "ROY M J",
    "ROYER H N",
    "RUDNICK R L",
    "RUDNICKI S",
    "RUDOLPH A K",
    "RUIZ T D",
    "RUNKEVICH Y",
    "RUPERT P",
    "RUPP L J",
    "RUSSELL J S",
    "RUTHERFORD K",
    "RYAN M J",
    "SABRA A A",
    "SACRAMENTO MO",
    "SAFINYA C R",
    "SAGHAZADEH S",
    "SAHA RAY R",
    "SAIKI C M",
    "SALAMI G",
    "SALDIVAR TANA",
    "SALEEM M",
    "SALEH O A",
    "SALEHUDDIN A",
    "SALEM L G",
    "SALEM R M",
    "SALINAS M D",
    "SALMON N U",
    "SALTON-COX G",
    "SALTZMAN-LI K",
    "SALUSCHEV S",
    "SALUSHCHEV S",
    "SALZMAN J E",
    "SAMBADO S B",
    "SAMOLSKY R E",
    "SAMUEL C E",
    "SAMUELS R D",
    "SANCHEZ A",
    "SANCHEZ C A",
    "SANCHEZ D",
    "SANCHEZ M",
    "SANDERSON N",
    "SANDOVAL C",
    "SANDOVAL N I",
    "SANTANA J",
    "SANTORO A E",
    "SARAJIAN G P",
    "SARKAR B",
    "SARQUILLA L S",
    "SARVER J",
    "SATTERTHWAITE",
    "SATTIN-BAJAJ",
    "SAUR E H",
    "SAURET A O",
    "SCALZO J N",
    "SCANLON C A",
    "SCHAEFFER J L",
    "SCHIMEL J P",
    "SCHLEY N B",
    "SCHMEDAKE A J",
    "SCHMIDT B S",
    "SCHMIDT E M",
    "SCHMITT R J",
    "SCHNEIDER B E",
    "SCHNEIDER N J",
    "SCHOINOPLOKAK",
    "SCHOOLER J W",
    "SCHOPP N",
    "SCHOW C L",
    "SCHOWALTER D",
    "SCHRANCK J B",
    "SCHUCK R K",
    "SCHULLER J A",
    "SCHULTZ J M",
    "SCOTT S L",
    "SCOTT T D",
    "SCOTT V",
    "SCRUGGS M A",
    "SCUDDER S L",
    "SEARS D W",
    "SEEBER A R",
    "SEET A M",
    "SEGAL N A",
    "SEGALMAN R A",
    "SEGURA D A",
    "SEHAYEK S B",
    "SEIBOLD D R",
    "SEIJO M A",
    "SEIKALY S R",
    "SELTMANN K",
    "SEN P",
    "SENTHILKUMAR",
    "SEPUNARU L",
    "SESHADRI R",
    "SEVILLA P C",
    "SHACKLEY M J",
    "SHAFIUZZAMAN",
    "SHAFROTH W G",
    "SHAH S",
    "SHAHANDEH M P",
    "SHAILJA F",
    "SHAKERIAN S",
    "SHANKAR S C",
    "SHARKEY J D",
    "SHATSKIKH E",
    "SHAW-HEY A",
    "SHEA J",
    "SHEARD M",
    "SHEEDY M A",
    "SHEFFIELD C A",
    "SHELL M S",
    "SHEN R",
    "SHEPPARD W D",
    "SHEREEN SAKR",
    "SHERMAN D A",
    "SHERRARD R W",
    "SHERWIN M S",
    "SHERWOOD T P",
    "SHEWRY T J",
    "SHIFLEY T H",
    "SHILO A",
    "SHINAGAWA C",
    "SHISHIM M D",
    "SHKOLNIK A D",
    "SHLOMI S",
    "SHOEMAKER T G",
    "SHRAIMAN B I",
    "SIBLEY C M",
    "SIDERIS L H",
    "SIDERIS T C",
    "SIEGEL D A",
    "SIEGEL G D",
    "SIINO R",
    "SIMMS A R",
    "SIMPSON E B",
    "SIMPSON J H",
    "SINGER G H S",
    "SINGH A K",
    "SINGH SATYAJ",
    "SINGHANIA V",
    "SINTURA M C",
    "SISCO Z D",
    "SIT K K",
    "SIWAJU F",
    "SKENAZI E C",
    "SLADE A M",
    "SLOAN T F",
    "SMALL A L",
    "SMALL P A",
    "SMILEY B T",
    "SMITH E K",
    "SMITH E R",
    "SMITH G L",
    "SMITH H M",
    "SMITH I",
    "SMITH J S",
    "SMITH K A",
    "SMITH S L",
    "SMITH S R",
    "SMITH S T",
    "SMITH W",
    "SMYTH L M",
    "SNEDIKER T B",
    "SNYDER C L",
    "SODHI S",
    "SOLERI D",
    "SOLGI M",
    "SOLIS B",
    "SOLIS S W",
    "SOLONE C J",
    "SONG K",
    "SONNINO P M",
    "SORAPURE M I",
    "SORDILLO D C",
    "SORENSON A H",
    "SORIANO K M",
    "SORIN C R",
    "SORKIN JENNI",
    "SOTO O F",
    "SPECK J S",
    "SPEER J M",
    "SPENCER M H",
    "SPERA F J",
    "SPICKARD P R",
    "SPIEKER S",
    "SPIESS M I",
    "SPIEVAK J S",
    "SPRAGUE T C",
    "SPRANDIO S R",
    "SPRATT R M",
    "SPRIGGE M A",
    "SQUIRES T M",
    "SRA M",
    "SREDNICKI M",
    "STAHL A",
    "STANSELL A",
    "STARR B J",
    "STARTZ R",
    "STEAVU-BALINT",
    "STEFKOVA R",
    "STEGEMOELLER",
    "STEIGERWALD D",
    "STEIN D A",
    "STEIN D P",
    "STEIN E A",
    "STEINKELLNER",
    "STEMMER S",
    "STEPHENS C G",
    "STEPHENSON J",
    "STEVENS V E",
    "STEVENSON-MIC",
    "STEWART J C",
    "STIER A C",
    "STIFEL S W",
    "STOHL C",
    "STOHL M S",
    "STOHLER J E",
    "STOKES L C",
    "STOLL H M",
    "STONE D",
    "STOPPLE J",
    "STORY D E",
    "STOTTS M L",
    "STOWERS R S",
    "STOYAN T",
    "STRAMPELLI G",
    "STRATAN S",
    "STRATHMAN B A",
    "STRATTON E C",
    "STREICHAN S",
    "STRELICH J H",
    "STROBEL M",
    "STROBEL N E",
    "STRONGMAN R D",
    "STRUKOV D B",
    "STUART C",
    "STUART D D",
    "STUCKY G D",
    "STURM I N",
    "STURMAN P C",
    "STUSSY C",
    "SU J",
    "SU J M",
    "SUAREZ F",
    "SUASSUNA SIMO",
    "SUBRAMONI R",
    "SUGAWARA H",
    "SUH S",
    "SUN C",
    "SUN D",
    "SUN H",
    "SUN SHAN-WEI",
    "SUN T",
    "SUN X",
    "SUN Y",
    "SUNG B O",
    "SURE E",
    "SURI S",
    "SURIANARAYANA",
    "SUSKO T G",
    "SUTTON J R",
    "SVADLENAK N D",
    "SWALEC C M",
    "SWEENEY S H",
    "SWEET S S",
    "SWENSON J S",
    "SYLVESTER B M",
    "SZETO H R",
    "SZMURLO D A",
    "SZUMLINSKI K",
    "TABATABAI-YAZ",
    "TABER P K",
    "TAGHAVI I",
    "TAGUE C",
    "TAHA R",
    "TAKATORI S",
    "TAKKINEN J H",
    "TAMURA Y",
    "TANG S",
    "TANIMOTO T",
    "TANLIMCO J L",
    "TARGINO R D",
    "TARIKERE ASHO",
    "TARTT E L",
    "TASCHIAN H J",
    "TASHMAN A P",
    "TAUBE J A",
    "TAVARES P C",
    "TAVES A",
    "TAYLOR C J",
    "TAYLOR C M",
    "TAYLOR V",
    "TAZHITDINOVA",
    "TCHAROS S S",
    "TEEL A R",
    "TEJEDA A",
    "TELLES E E",
    "TELLEZ C M",
    "TERRELL C J",
    "TESSARO S M",
    "TETTEGAH S Y",
    "THALER K M",
    "THANDI S",
    "THEBAUD S E",
    "THEOGARAJAN L",
    "THIBDEAU J C",
    "THOLL A A",
    "THOMAS A A",
    "THOMAS B T",
    "THOMAS C",
    "THOMAS C M",
    "THOMAS C T",
    "THOMAS-MCGILL",
    "THOMASSON K M",
    "THOMPSON A M",
    "THOMPSON GONZ",
    "THOMPSON M E",
    "THOMPSON W K",
    "THOMSEN C A",
    "THOMSON J A",
    "THONNART M M",
    "THORNBURG M E",
    "THORNTON S A",
    "THRAMPOULIDIS",
    "THROWER D A",
    "THURMAN N B",
    "TIAN W",
    "TICHAVAKUNDA",
    "TIFFNEY B H",
    "TILMAN G D",
    "TING J",
    "TINSLEY O N",
    "TITCOMB G C",
    "TOBAR TOBAR C",
    "TOBER T L",
    "TODD S J",
    "TOOBY J",
    "TORGUL E",
    "TORIBIO A G",
    "TORRES R D",
    "TORSIGLIERI A",
    "TRAN T N",
    "TREBESCH HEBE",
    "TREVINO VERAS",
    "TRINCADO MURU",
    "TRIOZZI N",
    "TRIPSAS M",
    "TRISAL A V",
    "TROTT T J",
    "TRUGMAN A T",
    "TRUJANO OCHOA",
    "TRUJILLO S G",
    "TRUSCELLI N I",
    "TRZASKOMA S M",
    "TSAI D",
    "TSAI G T",
    "TSAI P B",
    "TSAO S",
    "TSAY K",
    "TSIKEWA A F",
    "TSOULOUFAS G",
    "TSOUNA V",
    "TSUCHIYA Y",
    "TU K-C",
    "TUCKNOTT R A",
    "TUDISCO J J",
    "TUERKOEN M M",
    "TUMEN M E",
    "TUNC E",
    "TURNER T L",
    "TUROWETZ J",
    "TURSI G",
    "TWINE F W",
    "TY E",
    "TYBJERG D M",
    "TYBURCZY J L",
    "TYLER C M",
    "TYRRELL B P",
    "UGORETZ K M",
    "UHRIG R A",
    "UJEED S",
    "URCAREGUI M J",
    "URUCI X",
    "VAFA F",
    "VAGT C",
    "VALADEZ A M",
    "VALDEZ V E",
    "VALENCIA RAMI",
    "VALENTINE D L",
    "VALENTINE M T",
    "VAN DE WALLE",
    "VAN DEN ABBEE",
    "VAN DER HOEVE",
    "VAN DER VEEN",
    "VAN DER VEN A",
    "VAN DOORNE T",
    "VAN KOPPEN P",
    "VANCHELLA E C",
    "VANDERPOOL J",
    "VANDERWARKER",
    "VANDEVEER J B",
    "VARBLE M R",
    "VARGA K C",
    "VASQUEZ A",
    "VASQUEZ K E",
    "VAZQUEZ-BARE",
    "VEGA J C",
    "VENEGAS C",
    "VENTAYOL BOAD",
    "VERNON T W",
    "VERTIZ V",
    "VESPA E I",
    "VESTAL M A",
    "VICTORIAN J M",
    "VIGNA G",
    "VIGODA E J",
    "VIJAY K",
    "VILANDER B A",
    "VILLANUEVA-NI",
    "VISELL Y",
    "VIVIAN D A",
    "VLCEK V",
    "VO K T",
    "VON MIRBACH H",
    "VON WALD K",
    "VOOS A C",
    "VOSS K A",
    "VOSS M",
    "VYAS M M",
    "WAGNER Z J",
    "WAHLBERG D D",
    "WAHLERT G A",
    "WAID C J",
    "WAINWRIGHT B",
    "WAITE J H",
    "WAKIDI H",
    "WALD A P",
    "WALKER D S",
    "WALKER I J",
    "WALKER J R",
    "WALLACE V A",
    "WALLER I A",
    "WALSH C",
    "WALSH K J",
    "WALTER K V",
    "WALTHER J B",
    "WAN Z",
    "WANG G",
    "WANG JING",
    "WANG L C",
    "WANG L H",
    "WANG M",
    "WANG P T",
    "WANG R K",
    "WANG Y F",
    "WANG Y W",
    "WANG Y-D",
    "WANG YUXIANG",
    "WANG ZHEN",
    "WARD E J",
    "WARD JANE",
    "WARE R T",
    "WARWICK N L",
    "WASHBURN L",
    "WASSON C F",
    "WASSON S H",
    "WATERBURY A T",
    "WATERS E A",
    "WATTLES M",
    "WEAR R S",
    "WEBB M C",
    "WEBB M T",
    "WEBBER M A",
    "WEBBER M E",
    "WEBER E",
    "WEBER R",
    "WEI C",
    "WEI G",
    "WEIDNER C C",
    "WEIGLER E A",
    "WEIMBS T",
    "WEIR E A",
    "WELD D M",
    "WELD S P",
    "WELDEAB S",
    "WELLS A K",
    "WELLS S B",
    "WELTER V W",
    "WELTY L A",
    "WENG W W",
    "WERTH S",
    "WESTMACOTT B",
    "WHITAKER D R",
    "WHITE D G",
    "WHITE D W",
    "WHITE J S",
    "WHITE K D",
    "WHITED B S",
    "WHITEHEAD K A",
    "WHITESIDES K",
    "WHITESTONE S",
    "WHITTET E O",
    "WICKE J A",
    "WIDICK R E",
    "WILBANKS E G",
    "WILHOITE K A",
    "WILKENFELD N",
    "WILKINSON R C",
    "WILLETT B M",
    "WILLIAMS A M",
    "WILLIAMS D L",
    "WILLIAMS M L",
    "WILLIAMS O B",
    "WILLIAMS R C",
    "WILLIAMS S",
    "WILLIS C M",
    "WILSON B M",
    "WILSON G D",
    "WILSON M Z",
    "WILSON S D",
    "WILTON M B",
    "WINANT H",
    "WINDER T J",
    "WINTER R E",
    "WISEMAN W A",
    "WITTMAN R K",
    "WOHL H L",
    "WOLFE C C",
    "WOLFSON E R",
    "WOLSKI R M",
    "WOLTZ C R",
    "WONG T",
    "WONG Y",
    "WOOD Z J",
    "WOODS M",
    "WOODS M J",
    "WOODS V E",
    "WOOTEN T L",
    "WRIGHT P R",
    "WROBEL A J",
    "WU CHAO-YING",
    "WU D C",
    "WU G C",
    "WU V",
    "WU Y",
    "WUEBBEN D L",
    "WYMAN A J",
    "WYSS A R",
    "XU C",
    "XU H",
    "XU T",
    "YAKUSHKO O F",
    "YAMAMOTO NAOK",
    "YAMAUCHI Y",
    "YAMBOLIEV K I",
    "YAN J",
    "YAN L",
    "YAN X",
    "YANG H T",
    "YANG M",
    "YANG T",
    "YANG XU",
    "YANG Y",
    "YANG YOORI",
    "YAQUB S",
    "YASUDA K",
    "YE R",
    "YEGHNAZAR P Y",
    "YERKES K M",
    "YEUNG E H",
    "YI S",
    "YOON H",
    "YOON S",
    "YORK R A",
    "YOUK S",
    "YOUNG A F",
    "YOUNG C",
    "YOUNG H S",
    "YOUNG K",
    "YOUNG M R",
    "YU G",
    "YU H",
    "YU H-J",
    "YU J",
    "YU P",
    "YU YIN",
    "YUAN JIAOYUE",
    "YUKSEL S",
    "ZACKRISON E J",
    "ZADEH A E",
    "ZAHN S E",
    "ZAKARIAN A S",
    "ZALEHA S",
    "ZANGER D",
    "ZARATE A D",
    "ZAZZARINO M",
    "ZEE A",
    "ZENTENO J I",
    "ZETZER H A",
    "ZHANG LIMING",
    "ZHANG W",
    "ZHANG XINYI",
    "ZHANG Y",
    "ZHANG YITANG",
    "ZHANG YUEXIN",
    "ZHANG Z",
    "ZHAO X",
    "ZHAO XIAOLEI",
    "ZHAO YANG",
    "ZHENG X",
    "ZHONG S",
    "ZHOU E",
    "ZHOU HANMING",
    "ZHOU XIN",
    "ZHU M",
    "ZHU X",
    "ZHU Y",
    "ZHU ZIMU",
    "ZILZ Z L",
    "ZIMET M J",
    "ZIMMAN L",
    "ZIMMERMAN A Z",
    "ZIMMERMAN D S",
    "ZIPPERSTEIN S",
    "ZISA J E",
    "ZISERMAN P",
    "ZOK F",
    "ZOLLETT E",
    "ZONOUZI L",
    "ZSHORNACK M F",
    "ZULUETA B C",
    "ZUO Y",
    "ZYLSTRA S J",
  ];

  const handleKeyPress = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter") {
      handleEnterPress();
    }
  };

  const handleEnterPress = () => {
    if (!validWords.includes(inputValue.toUpperCase())) {
      alert("invalid");
    } else {
      handleClear();
      onInputChange(inputValue);
    }
  };

  const handleClear = () => {
    // Clear the textbox
    setInputValue("");
  };

  const handleChildInputChange = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const newValue = event.target.value;
    setInputValue(newValue);
    // Pass the input value to the parent component
  };

  return (
    <div>
      <div className="button">
        <input
          type="text"
          value={inputValue}
          onChange={handleChildInputChange}
          onKeyDown={handleKeyPress}
          style={{ color: "black" }}
        />
        <DropdownMenu
          options={validWords}
          onSelect={handleOptionSelect}
        ></DropdownMenu>
      </div>
      <div className="button">
        <button onClick={handleEnterPress}>Submit</button>
      </div>
    </div>
  );
};
