"use client";
import React, { useState } from "react";

interface TextInputProps {
  onInputChange: (newValue: string) => void;
  options: string[];
}
export const TextInput: React.FC<TextInputProps> = ({
  onInputChange,
  options,
}) => {
  const [inputValue, setInputValue] = useState("");

  const handleOptionClick = (selectedOption: string) => {
    setIsFocused(false);
    setInputValue(selectedOption);
  };

  const validWords = [
    "ABRA, GORDON",
    "ABU-OMAR, MAHDI",
    "ACKERT, LIZ",
    "ACOSTA-ALVEAR, DIEGO",
    "ADAMS, BRANDEN",
    "AFARY, JANET",
    "AFIFI, TAMMY",
    "AFIFI, WALID",
    "AGBOOLA, ADEBISI",
    "AGRAWAL, DIVYAKANT",
    "AHMAD, AHMAD",
    "AHUJA, AMIT",
    "AKEMANN, CHARLES",
    "ALBADA, NICOLE",
    "ALESSIO, PAUL",
    "ALIZADEH, MAHNOOSH",
    "ALVES, JAIME",
    "AMAR, PAUL",
    "AMIHAY, ARYEH",
    "ANANTH, PRABHANJAN",
    "ANDERS, ALLISON",
    "ANDERSON, KEVIN",
    "ANDERSON, OHAN",
    "ANDREA, BERNADETTE",
    "ANYIKA, MERCY",
    "APPEL, IRWIN",
    "ARIAS, CAROLINA",
    "ARMBRUSTER-SANDOVAL, RALPH",
    "ARMISTEAD, KATYA",
    "ARONOVA, ELENA",
    "ARYA, DIANA",
    "ASCHE, CHARLES",
    "ASHBY, FRANK",
    "ATHAYDE, MANAÍRA",
    "ATZBERGER, PAUL",
    "AVETISYAN, ZHIRAYR",
    "AWRAMIK, STANLEY",
    "AZARENKO, OLGA",
    "BAILLARGEON, KATIE",
    "BAKER, ANDREW",
    "BALDWIN, JOHN",
    "BALDWIN, JANICE",
    "BALKIND, JONATHAN",
    "BAMBACH, PAUL",
    "BANKS, INGRID",
    "BAPAT, SUDEEP",
    "BARBIERI-LOW, ANTHONY",
    "BARNES, DAMIEN",
    "BARNWELL, BRENDAN",
    "BARRAGE, LINT",
    "BARRETT, THOMAS",
    "BASHI TREITLER, VILNA",
    "BATISTE, STEPHANIE",
    "BEAMAN, JEAN",
    "BECKER, MARC",
    "BECKMAN, LAUREL",
    "BEDARD, KELLY",
    "BEGLEY, MATTHEW",
    "BELDING, ELIZABETH",
    "BELLOMI, JEFFREY",
    "BELTZ, ERIC",
    "BELTZ, GLENN",
    "BENELLI, CINDY",
    "BENZARTI, YOUSSEF",
    "BERENSTEIN, DAVID",
    "BERGSTROM, RANDY",
    "BERGSTROM, TED",
    "BERNARD, MICHAEL",
    "BERNSTEIN, HILARY",
    "BERNT, CHRISTOPHER",
    "BEYELER, MICHAEL",
    "BIBILASHVILI, TENGIZ",
    "BIGELOW, STEPHEN",
    "BIMBER, BRUCE",
    "BIRCHENALL, JAVIER",
    "BIRNIR, BJORN",
    "BLAES, OMER",
    "BLAKE, FELICE",
    "BLANKHOLM, JOSEPH",
    "BLOOM, PETER",
    "BLUMENTHAL, DEBRA",
    "BLURTON, HEATHER",
    "BOBO, JACQUELINE",
    "BODDY, AMY",
    "BOGART, KAREN",
    "BOHN, HENNING",
    "BOSCAGLI, MAURIZIA",
    "BOTHRA, SHIVANI",
    "BOULEY, BRAD",
    "BOURNE, JANET",
    "BOUWMEESTER, DIRK",
    "BOWERS, JOE",
    "BOWERS, MIKE",
    "BOWMAN, INGRID",
    "BRAININ, RISA",
    "BRECHER, BENJAMIN",
    "BREMSER, CHARLOTTE",
    "BRENNER, MARY",
    "BREWER, FORREST",
    "BRIDGES, TRISTAN",
    "BRIGGS, CHERIE",
    "BRIGHTBILL, JEREMY",
    "BROWN, FRANK",
    "BROWN, KARA MAE",
    "BROWN, MICHELLE",
    "BROWNING, RANDALYN",
    "BRUHN, KATHLEEN",
    "BRUSUTTI, ANNA",
    "BULTAN, TEVFIK",
    "BURATTO, STEVE",
    "BUSTO, RUDY",
    "BUTLER, ALISON",
    "BYL, KATIE",
    "CABEZON, JOSE",
    "CAMPAGNARI, CLAUDIO",
    "CAMPBELL, ERIC",
    "CAMPO, JUAN",
    "CANTRELL, AKIYO",
    "CAPETTINI, EMILIO",
    "CARLSON, CRAIG",
    "CARLSON, JULIE",
    "CARLSON, JEAN",
    "CARLSON, TOM",
    "CARTER, ANDREW",
    "CASE, SARAH",
    "CASILLAS, DOLORES",
    "CASSELS, SUSAN",
    "CAST, ALICIA",
    "CASTEELS, KAREL",
    "CASTILLO-MUNOZ, VERONICA",
    "CAYLOR, KELLY",
    "CENICEROS, HECTOR",
    "CEREZO, ALISON",
    "CHADA, JOE",
    "CHAJDAS, TYMOTEUSZ",
    "CHANDRASEKARAN, SHIV",
    "CHANG, ALENDA",
    "CHANG, SHIYU",
    "CHARNESS, GARY",
    "CHATTOPADHYAYA, UTATHYA",
    "CHATTOPADHYAY, SWATI",
    "CHEN, ERIC",
    "CHEN, HUACHEN",
    "CHEN, IRENE",
    "CHEN, SHU-CHUAN (BELLA)",
    "CHEN, TAO",
    "CHIKOWERO, MHOZE",
    "CHMELKA, BRADLEY",
    "CHO, ALEXANDER",
    "CHO, GUNHEE",
    "CHOI, EUNJIN",
    "CHRISTOFFERSEN, ROLF",
    "CHU, VENA",
    "CLARK, JORDAN",
    "CLARKE, KEITH",
    "CLEGG, DENNIS",
    "CLEMENCON, RAYMOND",
    "COBURN, KATIE",
    "COGGINS, BRIDGET",
    "COHEN, BENJAMIN",
    "COLAHAN, NANCY",
    "COLLINS, NANCY",
    "CONRAD, PHILL",
    "CONROY-BEAM, DANIEL",
    "COOK, ELIZABETH",
    "COOLEY, TIM",
    "COOPER, DARYL",
    "CORONA, KEITH",
    "COSMIDES, LEDA",
    "COTICH, CRAIG",
    "COVO, MANUEL",
    "CRAIG, KATY",
    "CRAIG, NATHANIEL",
    "CRICKETTE, MARIA",
    "D'ANCA, CHRISTENE",
    "D'ANTONIO, CARLA",
    "DAI, XIANZHE",
    "DALY, SAMANTHA",
    "DAMLUJI, MONA",
    "DANIEL, REGINALD",
    "DASGUPTA, DEBANUJ",
    "DAVISON, RAZIEL",
    "DE CARVALHO, LEILA",
    "DE CHAISEMARTIN, CLEMENT",
    "DEAN, CHRISTOPHER",
    "DELOMBARD, JEANNINE",
    "DESCHENES, OLIVIER",
    "DESHMUKH, RANJIT",
    "DETERING, NILS",
    "DEVRIES, TIMOTHY",
    "DEWAR, TIM",
    "DEY, SIDDHARTH",
    "DIAZ SANCHEZ, MICAELA",
    "DIGESER, ELIZABETH",
    "DIGESER, PAIGE",
    "DING, QINGHUA",
    "DING, YUFEI",
    "DODGE, SOMAYEH",
    "DOGIC, ZVONIMIR",
    "DOHERTY, MICHAEL",
    "DONELAN, JAMES",
    "DONNELLY, BRIAN",
    "DOUGLASS, JEREMY",
    "DOYLE, ADELE",
    "DRESSAIRE, EMILIE",
    "DRISKEL, DANA",
    "DUFFY, A",
    "DUNBAR, NORAH",
    "DUNCAN, IAN",
    "DUNN, FRANCIS",
    "DUOER, DAIGENGNA",
    "DUQUE, JASON",
    "DUTSCH, DOROTA",
    "EARDLEY, DOUGLAS",
    "EBENSTEIN, ALAN",
    "EBRAHIM, EBRAHIM",
    "ECKSTEIN, MIGUEL",
    "EDGAR, ADRIENNE",
    "EILON, ZACHARY",
    "EK, AULI",
    "EL ABBADI, AMR",
    "ELISON, WILLIAM",
    "ELIZONDO, SONNY",
    "ENGEL, EMILY",
    "ERICKSON, BRICE",
    "ERNST, BRIAN",
    "ESPONDA, IGNACIO",
    "EVANS, MARSHALL",
    "EVELYN, CHRISTOPHER",
    "EVEN, THOMAS",
    "FALASCA, SIMONETTA",
    "FALVEY, KEVIN",
    "FANCHER, PATRICIA",
    "FEINSTEIN, STUART",
    "FELANDO, CYNTHIA",
    "FELDMAN, LESLIE J.",
    "FELDMAN, RAISA",
    "FELDWINN, DARBY",
    "FELIX, ERIKA",
    "FENG, YU",
    "FERNANDEZ, PATRICIO",
    "FIGUEREDO, OMAR",
    "FINKELSTEIN, RUTH",
    "FITCH, ROB",
    "FLANAGIN, ANDREW",
    "FOLTZ, KATHY",
    "FONTAINE, SAM",
    "FORAN, JOHN",
    "FORD, KATERINA",
    "FORD, PETER",
    "FRANK, DANIEL",
    "FRANKS, ALEXANDER",
    "FREDRICKSON, GLENN",
    "FREEMAN, LAURIE",
    "FREUND, ERNEST",
    "FRIDLUND, ALAN",
    "FROEHLICH, HALLEY",
    "FRUHSTUCK, SABINE",
    "FULKERSON, SCOTT",
    "FYGENSON, DEBORAH",
    "GABLE, SHELLY",
    "GABRIEL, VIKTORIA",
    "GABRIELE, GUY",
    "GAINER, MORGAN",
    "GALLUCCI, RALPH",
    "GANS, PHIL",
    "GARCIA, MARIO",
    "GARCIA-MARTINEZ, MARC",
    "GARFIELD, PETER",
    "GARR, W.RANDALL",
    "GARRATT, ROD",
    "GAULIN, STEVEN",
    "GELLER, ROBERT",
    "GENOVA, GINA",
    "GHOSH, BISHNUPRIYA",
    "GIBBS, JENNIFER",
    "GIBOU, FREDERIC",
    "GIDDING, AARON",
    "GIDDINGS, STEVE",
    "GIESBRECHT, BARRY",
    "GILBERT, JOHN",
    "GILMORE, TIMOTHY",
    "GOARD, MICHAEL",
    "GODDARD, TUG",
    "GONZALES, AMY",
    "GONZALEZ, NINO",
    "GOODEARL, KEN",
    "GOODWIN, JON",
    "GOPALAN, GIRI",
    "GORDON, MICHAEL",
    "GOULIAS, KOSTAS",
    "GRAVES, GREGORY",
    "GRIFFIN, ANDREW",
    "GRIFFITH, BRIAN",
    "GRIPPO, JIM",
    "GROSS, STEVEN",
    "GROVER, SUSAN",
    "GRUE, MICHELLE",
    "GU, MENGYANG MICHEAL",
    "GUAN, DAOXIONG",
    "GUPTA, ARPIT",
    "GUPTA, TRINABH",
    "GURUSWAMY, SATHYA",
    "GURVEN, MICHAEL",
    "GUTIÉRREZ-MAGALLANES, DR. COCO",
    "GUYTON ACOSTA, KILEY",
    "HABER, BARON",
    "HAI, YANG",
    "HAJDA, JOHN",
    "HALMRAST, DANIEL",
    "HAMILTON, KRISTY",
    "HAMMER, LESLIE",
    "HAN, SONG-I",
    "HANSEN, GARY",
    "HANSER, MATTHEW",
    "HANSON, JEFFREY",
    "HARDEKOPF, BEN",
    "HARMON, C J",
    "HARRIS, DEBORAH",
    "HARTMAN, JOHN",
    "HARUTYUNYAN, DAVIT",
    "HASHIMOTO, KUMI",
    "HAUGHTON, CHANTEL",
    "HAYES, CHRIS",
    "HAYNES, REAGAN",
    "HAYTON, TREVOR",
    "HE, JINGYI",
    "HECHT, RICHARD",
    "HEGARTY, MARY",
    "HELGESON, MATTHEW",
    "HELLIER-TINOCO, RUTH",
    "HENDERSON, JARETT",
    "HILLIS, GREG",
    "HILTNER, KENNETH (KEN)",
    "HIRSCH, SARAH",
    "HOBBS-MORGAN, CHASE",
    "HODGES, SCOTT",
    "HOELLE, JEFFREY",
    "HOFMANN, GRETCHEN",
    "HOFMANN, MICHAEL",
    "HOLBROOK, SALLY",
    "HOLDEN, THOMAS",
    "HOLDREGE, BARBARA",
    "HOLLERER, TOBIAS",
    "HOLMES, DAWN",
    "HOLT, JENNIFER",
    "HOLTON, JARED",
    "HOM, STEPHANIE MALIA",
    "HOROWITZ, GARY",
    "HOU, LYNN",
    "HU, RUIMENG",
    "HUANG, YUNTE",
    "HUISGEN-ZIMMERMAN, BIRGE",
    "HUK, PETER",
    "HUSTON, VALERIE",
    "ICHIBA, TOMOYUKI",
    "IGLESIAS-RODRIGUEZ, DEBORA",
    "IHM, ELLIOTT",
    "JACKSON, MATT",
    "JACKSON, WENDY",
    "JACOB, WALTER",
    "JACOBS, EMILY",
    "JACOBS, RICADO",
    "JACOBSON, LISA",
    "JACQUES, GEOFFREY",
    "JAEGER, LUC",
    "JAMES, ANNA",
    "JAMMALAMADAKA, SREENIVASA",
    "JANOWICZ, KRZYSZTOF",
    "JANUSONIS, SKIRMANTAS",
    "JARRETT, GREG",
    "JAYICH, ANDREW",
    "JAYICH, ANIA",
    "JENKINS, CHRIS",
    "JEVBRATT, LISA",
    "JI, CHEN",
    "JIN, CHENHAO",
    "JOHNSON, GREG",
    "JOHNSON, JENNIFER",
    "JONES, CHARLES",
    "JOSEPH, CRISJOE",
    "JOSHI, PRADEEP",
    "JUE, MELODY",
    "JURKOWSKI, NICOLAS",
    "KAHN, KALJU",
    "KALMAN, LAURA",
    "KAM, JENNIFER",
    "KAPLAN, CYNTHIA",
    "KATSIKA, ARGYRO",
    "KATZ, DEREK",
    "KAUFFMAN, MITCHELL",
    "KEARNEY, J J",
    "KEIFLIN, RON",
    "KELLER, ARTURO",
    "KELLER, EDWARD",
    "KENNEDY, ROBERT (BOB)",
    "KENNETT, DOUGLAS",
    "KEUM, TAE-YEOUN",
    "KHARITONOVA, YEKATERINA KATE",
    "KIM, BONGJIN",
    "KIM, HEEJUNG",
    "KIM, HYUN-JUNG",
    "KIM, SUNG SOO",
    "KIM, YOUNG JI",
    "KING, JENNIFER",
    "KING, RACHAEL",
    "KING, WILLIAM DAVIES",
    "KIPPIN, TOD",
    "KISLENKO, NATASHA",
    "KLEIN, STANLEY",
    "KLOKE, JOHN",
    "KOKINIS, TROY ARAIZA",
    "KORMAN, DANIEL",
    "KORNBERG, DANA",
    "KOSIK, KENNETH",
    "KOUTROULAKIS, GEORGIOS",
    "KOZERAWSKI, JEDRZEJ",
    "KRINTZ, CHANDRA",
    "KRISTIANSEN, KAI",
    "KRUEGEL, CHRIS",
    "KRUT, ROBERT",
    "KRUVAND, MARJORIE",
    "KUHN, PETER",
    "KUMAR, SANJAY",
    "KUNDU, MANNY",
    "KURIN, DANIELLE",
    "KURIS, ARMAND",
    "KYRATZIS, AMY",
    "LABATUT, MARION",
    "LABUTIN, DENIS",
    "LAMARTINE, NICOLE",
    "LANE, DAN",
    "LANSING, CAROL",
    "LARUE, RENAN",
    "LASHMET, AMY",
    "LATTO, JOHN",
    "LAURENT-PERRAULT, EVELYNE",
    "LAVERMAN, LEROY",
    "LAWSON, DAVID",
    "LEA, DAVID",
    "LEBRUN, ALEX",
    "LEE, JIN SOOK",
    "LEE, JOHN",
    "LEE, WONA",
    "LEVY, BENJAMIN",
    "LEWALLEN, ANN-ELISE",
    "LEWIS, ROBERT",
    "LI, PENG",
    "LI, XIAORONG",
    "LI, ZHIJIAN",
    "LIBERMAN, ZOE",
    "LIEN, PEI-TE",
    "LIM, GEUNHO",
    "LIN, QUYUAN",
    "LINDHEIM, SARA",
    "LIPMAN, EVERETT",
    "LIPSHUTZ, BRUCE",
    "LISIECKI, LORRAINE",
    "LIU, ALAN",
    "LIU, ZHENG",
    "LMAIFI, MARIAM",
    "LOAICIGA, HUGO",
    "LOHWASSER, KARIN",
    "LOKSHTANOV, DANIEL",
    "LONG, DARREN",
    "LOPEZ-CARR, DAVID",
    "LOUIS, MATTHIEU",
    "LOVETT, DUSTIN",
    "LOW, DAVID",
    "LOW, SENG",
    "LOWELL, JULIA",
    "LUBIN, PHILIP",
    "LUDKOVSKI, MICHAEL",
    "LUDWIG, ANDREAS",
    "LUNA, ZAKIYA",
    "LUNDBERG, SHELLY",
    "LUNSFORD, KAREN",
    "LUO, XIAO",
    "LUZZATTO-FEGIZ, PAOLO",
    "LYTLE, TIFFANY",
    "MA, DZWOKAI",
    "MACDONALD, FRANCIS",
    "MACIAS, ESMERALDA",
    "MACKIE, DIANE",
    "MACLEAN, ROSE",
    "MAHDAVI, PAASHA",
    "MAJEWSKI, JOHN",
    "MAJOR, BRENDA",
    "MALVINNI, DAVID",
    "MANIN, FEDYA",
    "MANJUNATH, B. S.",
    "MARCUS, SCOTT",
    "MARCUSE, HAROLD",
    "MARDEN, JASON",
    "MARINA, MAVEL",
    "MARKS, TREVOR",
    "MAROLF, DONALD",
    "MARQUES-PASCUAL, LAURA",
    "MARSHALL, KATHY",
    "MARTIN, CRYSTAL",
    "MASLAN, MARK",
    "MASSIE, ERIC",
    "MASTERSON, DANIEL",
    "MASTRO, DANA",
    "MATNI, ZIAD",
    "MAYER, RICHARD",
    "MAZANEC, THOMAS",
    "MAZIN, BENJAMIN",
    "MCAULEY, CHRISTOPHER",
    "MCCANTS, KRISTEN",
    "MCCARTHY, CHRISTINA",
    "MCCLAIN, KATIA",
    "MCCLURE, SARAH",
    "MCDONALD, KATE",
    "MCFADDEN, JOE",
    "MCFARLAND, ERIC",
    "MCHUGH, PATRICK",
    "MCKIRAHAN, RICHARD",
    "MCLELLAN, LARRY",
    "MCMAHON, CHRISTINA",
    "MCMEEKING, ROBERT",
    "MCMURTREY, MEGAN",
    "MCNAMARA, JAMES",
    "MEADOW, MARK",
    "MEIBURG, ECKART",
    "MEIRING, WENDY",
    "MELNICK, ROSS",
    "MENARD, GABRIEL",
    "MENDES BRAGA, MARTA",
    "MEROLLA, ANDY",
    "METIU, HORIA",
    "METZGER, MIRIAM",
    "MIELE, ILENE",
    "MIESCHER, STEPHAN",
    "MILDENBERGER, MATTO",
    "MILLER, KARLY",
    "MILLNER, ANTONY",
    "MINOR, RYAN",
    "MIOLANE, NINA",
    "MIRELES-RIOS, REBECA",
    "MIRZA, DIBA",
    "MITCHELL, GREG",
    "MIZRAHI, JANET",
    "MOELLER, HOLLY",
    "MOERSCHEL, JONATHAN",
    "MOKRISKI, DAVID",
    "MONAHAN, LAURIE",
    "MONTELL, CRAIG",
    "MONTELL, DENISE",
    "MONTELLO, DAN",
    "MOODY, GALAN",
    "MOORE, KATIE",
    "MOORE, KM",
    "MOOSBRUGGER, LORELEI",
    "MORALES, HELEN",
    "MORRIS, NOMI",
    "MORRISON, DAVE",
    "MORRISSEY, MEGHAN",
    "MORSE, JULIA",
    "MORSTEIN-MARX, ROBERT",
    "MORTON, CARLOS",
    "MOSELEY, DELILA",
    "MOULTON, SUSAN",
    "MOUTI, SAAD",
    "MUKHERJEE, ARNAB",
    "MULLATH, ZUHAIR",
    "MULLEN, JILLIAN",
    "MULLIN, CHARLES",
    "MULLIN, DOLLY",
    "MURNANE, EVAN",
    "MURRAY, ALAN",
    "MURTI-HALI, DIPALI",
    "MURUAMENDIARAZ, MAITANE",
    "MYERS, KAREN",
    "NABI, ROBIN",
    "NAGY, AKOS",
    "NAKAMURA, JESSICA",
    "NALL, CLAYTON",
    "NARANG, NEIL",
    "NATHAN, JON",
    "NELSON, HARRY",
    "NESCI, CATHERINE",
    "NEWFIELD, CHRIS",
    "NGUYEN, ALICE",
    "NGUYEN, THUC-QUYEN",
    "NICOLAESCU, ANDREA",
    "NIDZIEKO, NICK",
    "NOI, EVGENY",
    "NORRIS, ANDREW",
    "NOURIZADEH, SHANE",
    "NOVAK, DAVID",
    "O'CONNOR, ALICE",
    "O'MALLEY, MICHELLE",
    "OAKLEY, TODD",
    "OGRAIN, CHRISTOPHER",
    "OH, SANG-YUN",
    "OLGUIN, BEN",
    "OONO, RYOKO",
    "OPREA, RYAN",
    "ORTIZ, ARLENE",
    "OSQUEEZADEH, BAHRAM",
    "OXELSON, EVA",
    "PACHECO, RAQUEL",
    "PAJAK, ANNA",
    "PAN, JIAYIN",
    "PANDYA, SAMEER",
    "PARK, JEA-HYUN",
    "PARK, SOWON",
    "PARKER, EMMA",
    "PARKS, LISA",
    "PATTERSON, DAVID",
    "PATTERSON, KATHY",
    "PAUL, DAVID",
    "PEDERSEN, HAL",
    "PENLEY, CONSTANCE",
    "PENNATHUR, SUMITA",
    "PEREZ, ELIZABETH",
    "PERRONE, GIULIANA",
    "PETERS, GARETH",
    "PETRO, PATRICE",
    "PETTUS, THOMAS",
    "PIERCE, KANA",
    "PLANE, ANN",
    "PLAXCO, KEVIN",
    "PONCE, GUSTAVO",
    "POOLE, STEPHEN",
    "POPESCU, PAULA",
    "PORTER, MATT",
    "PORTER, SUSANNAH",
    "POWERS, REBECCA",
    "PRESS, CAROL",
    "PRICE, SCOTT",
    "PRIETO, ERIC",
    "PROPEN, AMY",
    "PROULX, STEPHEN",
    "PUTINAR, MIHAI",
    "QIN, CHENG-ZHONG",
    "QUIRK, MATTHEW",
    "RADFORD, ANTHONY",
    "RALEY, RITA",
    "RAMBELLI, FABIO",
    "RANA, SWATI",
    "RAPPAPORT, ERIKA",
    "RATNER, KYLE",
    "RAVAT, UMA",
    "RAVEN, MORGAN",
    "RAYMOND, ELENA",
    "RAYMOND, GEOFFREY",
    "READ DE ALANIZ, JAVIER",
    "REESE, BEN",
    "REEVE, DANIEL",
    "REICH, NORBERT",
    "REID, SCOTT",
    "REYNOLDS, DWIGHT",
    "RICE, RONALD",
    "RICHARDSON, CHRIS",
    "RICHARDSON, MATT",
    "RICHMAN, JEFF",
    "RIOS, VICTOR",
    "RIOUX, MATT",
    "ROBERTS, DAR",
    "ROBERTS, LUKE",
    "ROBERTSON, JOHN",
    "ROBERTSON, TERESA",
    "ROBINSON, WILLIAM",
    "RODRIGUEZ, CELIA",
    "RONEY, JAMES",
    "ROSE, KENNETH",
    "ROSS, ELISSA",
    "ROTHFARB, LEE",
    "ROTHMAN, JOEL",
    "ROYER, HEATHER",
    "RUIZ, TREVOR",
    "RUPERT, PETER",
    "RUTHERFORD, KEVIN",
    "SABRA, ADAM",
    "SAFINYA, CYRUS",
    "SALDIVAR, TANAKA",
    "SALEEM, MUNIBA",
    "SALEM, LOAI",
    "RAMMY, SALEM",
    "SALMON, NATHAN",
    "SALTON COX, GLYN",
    "SAMOLSKY, RUSSELL",
    "SAMUELS, ROBERT",
    "SANCHEZ, MICAELA DIAZ",
    "SANTORO, ALYSON",
    "SARKAR, BHASKAR",
    "SAUR, ELIZABETH",
    "SCHLEY, NATHAN",
    "SCHMITT, RUSSELL",
    "SCHNEIDER, NICK",
    "SCHOINOPLOKAKI, EMMANUELA",
    "SCHOOLER, JONATHAN",
    "SCHOW, CLINT",
    "SCHRANCK, JOHN",
    "SCHULLER, JON",
    "SHELL, SCOTT",
    "SCOTT, VICKIE",
    "SCUDDER, SAMANTHA",
    "SEGAL, NOAH",
    "SEGALMAN, RACHEL",
    "SEGURA, DENISE",
    "SEIKALY, SHERENE",
    "SEN, PRADEEP",
    "SEPUNARU, LIOR",
    "SHAKERIAN, SHAYA",
    "SHEA, JOAN",
    "SHEFFIELD, CHUCK",
    "SAKR, LAILA",
    "SHERMAN, DAVID",
    "SHERWIN, MARK",
    "SHERWOOD, TIMOTHY",
    "SHEWRY, TERESA",
    "SHILO, AMIT",
    "SHISHIM, MARK",
    "SHKOLNIK, ALEXANDER",
    "SIDERIS, TOM",
    "SIEGEL, GREG",
    "SIMPSON, JULIE",
    "SINGH, AMBUJ",
    "SINGH, SATYAJIT",
    "SISCO, ZACH",
    "SLOAN, TINA",
    "SMITH, ERIC",
    "SMITH, IKUKO",
    "SMITH, KENNETH",
    "SMITH, STEVE",
    "SMITH, STUART",
    "SMITH, WILLIAM",
    "SOLIS, SHARON",
    "SONNINO, PAUL",
    "SORAPURE, MADELINE",
    "SORIANO, KIMBERLY",
    "SPICKARD, PAUL",
    "SPRAGUE, THOMAS TOMMY",
    "SPRIGGE, MARTHA",
    "SQUIRES, TODD",
    "SRA, MISHA",
    "STANSELL, AMANDA",
    "STARTZ, RICHARD",
    "STEAVU-BALINT, DOMINIC",
    "STEIGERWALD, DOUG",
    "STEIN, DANIEL",
    "STEINKELLNER, CHERI",
    "STEVENSON, VITAS",
    "STEWART, JEFFREY",
    "STOHL, CYNTHIA",
    "STOHL, MICHAEL",
    "STOHLER, JASON",
    "STOKES, LEAH",
    "STOLL, HEATHER",
    "STOPPLE, JEFFREY",
    "STRATHMAN, BRENT",
    "STREICHAN, SEBASTIAN",
    "STROBEL, MARCEL",
    "STRUKOV, DMITRI",
    "STUART, CHARLES",
    "STUART, DAVID",
    "SU, JIANWEN",
    "SUGAWARA, HIROKO",
    "SUN, HALA",
    "SUN, YIDAN",
    "SUREAU, ELOISE",
    "SURI, SUBHASH",
    "SUSKO, TYLER",
    "SVADLENAK, NATHAN",
    "SWEENEY, STUART",
    "SWENSON, JULIE",
    "SYLVESTER, BRYANNA",
    "SZUMLINSKI, KAREN",
    "TAKATORI, SHO",
    "TANG, SUI",
    "TANIMOTO, TOSHIRO",
    "TARIKERE, ASHWIN",
    "TAYLOR, CATHERINE",
    "TAZHITDINOVA, ALISA",
    "TCHAROS, STEFANIE",
    "TELLES, EDWARD",
    "THOLL, ANDREW",
    "THOMAS, CHRISTIAN",
    "THOMAS, CHRISTINE",
    "THOMAS, CATHY",
    "THOMASSON, KELLY",
    "THOMPSON, WILLIAM",
    "TIAN, WENCHUAN",
    "TIFFNEY, BRUCE",
    "TINSLEY, OMISE'EKE",
    "TOBER, TARA",
    "TOOBY, JOHN",
    "TRUGMAN, ANNA",
    "TRUSCELLI, NIKKI",
    "TSAI, DANNY",
    "TSAI, GEOFFREY",
    "TSOUNA, VOULA",
    "TURNER, THOMAS L.",
    "TUROWETZ, JASON",
    "TWINE, FRANCE WINDDANCE",
    "TYBJERG, DANIEL",
    "TYBURCZY, JENNIFER",
    "TYLER, CLAUDIA",
    "VALENTINE, DAVE",
    "VALENTINE, MEGAN",
    "VAN KOPPEN, PETRA",
    "VANDERWARKER, AMBER",
    "VAZQUEZ-BARE, GONZALO",
    "VENEGAS, CHRISTINA",
    "VERNON, TY",
    "VIGNA, GIOVANNI",
    "VIGODA, ERIC",
    "VILLANUEVA-NIEVES, NATALIA",
    "VLCEK, VOJTECH",
    "VYAS, MAHARSHI",
    "WAID, CANDACE",
    "WAINWRIGHT, BRIAN",
    "WALKER, DAVID",
    "WALKER, JANET",
    "WALLACE, VESNA",
    "WALSH, CASEY",
    "WALTHER, JOE",
    "WANG, MIAN",
    "WANG, RICHERT",
    "WANG, YUAN-FANG",
    "WANG, WILLIAM",
    "WANG, YU-XIANG",
    "WARE, RUDOLPH",
    "WARWICK, NICOLE",
    "WATERBURY, ADAM",
    "WATTLES, MIRIAM",
    "WEBB, MARIE",
    "WEBBER, MARTHA",
    "WEBER, ELISABETH",
    "WEBER, RENE",
    "WEI, GUFONG",
    "WEIMBS, THOMAS",
    "WELD, DAVID",
    "WELD, SARA PANKENIER",
    "WELDEAB, SYEE",
    "WELTY, LILY ANNE YUMI",
    "WESTMACOTT, BRIANA",
    "WHITE, JEREMY",
    "WHITEHEAD, KEVIN",
    "WHITESTONE, STEPHENSON",
    "WHITTET, ELLEN",
    "WICKE, JENNIFER",
    "WILKENFELD, NAN",
    "WILLIAMS, ALISON",
    "WILSON, BRENT",
    "WILSON, GREG",
    "MUSE, WILSON",
    "WILTON, MIKE",
    "WINANT, HOWARD",
    "WINDER, TERRELL",
    "WITTMAN, RICHARD",
    "WOHL, HANNAH",
    "WOLFE, CHARLES",
    "WOLFSON, ELLIOT",
    "WOLSKI, RICH",
    "WOODS, VANESSA",
    "WOOTEN, TERRANCE",
    "WUEBBEN, DANIEL",
    "WYSS, ANDRE",
    "XU, CENKE",
    "YAMAMOTO, NAOKI",
    "YAMBOLIEV, KALI",
    "YAN, LINGQI",
    "YAN, XIFENG",
    "YANG, HENRY",
    "YANG, TAO",
    "YANG, XU",
    "YAQUB, SALIM",
    "YASUDA, KIM",
    "YE, RICK",
    "YEUNG, ENOCH",
    "HWANG, YOON",
    "YOUNG, ANDREA",
    "YOUNG, HILLARY",
    "YOUNG, KAY",
    "YU, GUO",
    "YU, HONGBO",
    "YUKSEL, SEVGI",
    "ZACKRISON, ERIC",
    "ZAKARIAN, ARMEN",
    "ZANGER, DANIEL",
    "ZARATE, ADANARI",
    "ZEE, ANTHONY",
    "ZHANG, LIMING",
    "ZHANG, YITANG",
    "ZHANG, ZHENG",
    "ZHAO, XIAOLEI",
    "ZHENG, XIAOWEI",
    "ZHOU, HANMING",
    "ZHU, ZIMU",
    "ZIMMAN, LAL",
    "ZIMMERMAN, AARON",
    "ZIPPERSTEIN, STEVEN",
    "ZISERMAN, PAULINE",
    "ZULUETA, BENJAMIN",
    "ZYLSTRA, STEPHEN",
  ];

  const handleFocus = () => {
    setIsFocused(true);
  };

  const handleBlur = () => {
    setIsFocused(false);
  };

  const handleKeyPress = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter") {
      handleEnterPress();
    }
  };

  const handleEnterPress = () => {
    if (!validWords.includes(inputValue.toUpperCase())) {
      alert("Invalid name!");
    } else {
      handleClear();
      onInputChange(inputValue);
      setIsFocused(false);
    }
  };

  const handleClear = () => {
    // Clear the textbox
    setInputValue("");
  };
  const [filteredOptions, setFilteredOptions] = useState(options);

  const handleChildInputChange = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const newValue = event.target.value;
    setInputValue(newValue);

    const newFilteredOptions = options.filter((option) =>
      option.toLowerCase().includes(newValue.toLowerCase())
    );

    setFilteredOptions(newFilteredOptions);
  };

  const [isFocused, setIsFocused] = useState(false);

  return (
    <div>
      <div>
        <input
          type="text"
          value={inputValue}
          onClick={handleFocus}
          onChange={handleChildInputChange}
          onKeyDown={handleKeyPress}
          style={{ color: "black", width: "600px" }}
        ></input>
        <button className="subbutton" onClick={handleEnterPress}>
          {" "}
          Submit
        </button>
        {isFocused && (
          <div className="dropdownmain">
            <div className="dropdown-options">
              {filteredOptions.map((option) => (
                <div key={option} onClick={() => handleOptionClick(option)}>
                  {option}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
